postlund/pyatv

pyatv/daap.py
I introduced a bug with the login id changes that would result in an
additional & would be added at the end of URLs when only session id
is included. Some requests, like artwork, would fail for this.
=> Fix URL parameter bug

README.rst, docs/atvremote.rst, docs/connecting.rst, docs/finding_devices.rst, docs/index.rst, docs/pairing.rst, examples/pairing.py, pyatv/__init__.py, pyatv/__main__.py, pyatv/pairing.py, pyatv/tag_definitions.py, pyatv/tags.py, tests/test_dmap.py, tests/test_functional.py, tests/zeroconf_stub.py
Should work by using atvremote:
atvremote pair
And then add the remote on the Apple TV. Default pin is 1234 (which
must be correctly entered) and name is "pyatv remote". These settings
can be changed with parameters to atvremote. Currently a pairing
timer is set to 60 seconds, so the process must be finished within
that time.
NOTE: Before merging this, some work must be done with tearing down the webserver and zeroconf after the paring period is done. It currently leaks.
=> Add support for pairing

.gitignore, requirements_all.txt, setup.py, tox.ini
Dependencies must be listed in setup.py for setuptools to work
properly, so they have now moved from requirements_all.txt.
=> Restore requirements to fix setuptools

CHANGES.rst, docs/connecting.rst, pyatv/__init__.py, pyatv/airplay.py, pyatv/daap.py, tests/test_airplay.py
Instead of always creating a default ClientSession, it's now possible to
pass a custom one. If no session is given, a default one is created so
this change is backwards compatible.
=> Allow passing a custom session

README.rst, docs/index.rst, setup.py
Require the least-known-to-work version to minimize risk for dependency
problems for users. Fixes #42.
=> Unpin external dependencies

README.rst, docs/finding_devices.rst, pyatv/__init__.py, pyatv/__main__.py, pyatv/helpers.py, tests/test_functional.py
By passing abort_on_found when scanning, the process will abort even if the
timeout has not been reached. This is now default in atvremote and
pyatv.helpers.auto_connect. This fixes #19.
=> Support fast discovery if one device is found

pyatv/__main__.py
In the beginning it was used to ensure that commands did nog hang for
too long, but it doesn't work with long running tasks like AirPlay.
This fixes #68.
=> Remove wait_for with timeout in atvremote

pyatv/__main__.py, tests/test_airplay.py, tests/test_functional.py
It is now possible to specify multiple commands at the same time, which
decreases execution time a lot. An example:
atvremote -a topmenu right down menu menu
Note: Arrow keys, e.g. right and down, are not yet supported.
=> Multiple commands

README.rst, docs/index.rst, setup.py
Push updates stopped working around 1.3.2-1.3.4 but bug was fixed in
aiohttp 1.3.5. Also pin upper version so that < 3.0 is required.
=> Require at least aiohttp 1.3.5

pyatv/daap.py, pyatv/dmap.py, pyatv/internal/apple_tv.py, tests/fake_apple_tv.py, tests/test_dmap.py, tests/test_functional.py
This is the quick-n-easy solution where I ignore the fact that ATV3 does not seem to support these commands. But since it just ignores them I find it to be good enough since it does not increase complexity of handling multiple device types in the library.
I have not verified if this PR works since I don't own a gen 4 device, so if someone can help me with that I would be grateful. Will not merge until verification is done.
=> Support arrow keys for ATV4

pyatv/__init__.py, pyatv/__main__.py, pyatv/airplay/__init__.py, pyatv/airplay/player.py, pyatv/interface.py, pyatv/internal/apple_tv.py, tests/test_airplay.py, tests/test_functional.py
AirPlay will play a bigger part in the future, e.g. with device
authentication. Adding new features in a good way with current API is
pretty tough, so this change aims to make that easier by extracting
AirPlay to a separate public interface (similar to remote_control or
playing).
THIS IS A BREAKING CHANGE! The play_url has moved from remote_control
to airplay and all users must update their code.
=> Extract AirPlay code to separate interface

CHANGES.rst, pyatv/__main__.py, pyatv/interface.py, tests/test_interface.py
Previously when doing "atvremote commands", a device was needed and a
connection was made to it in order to figure out explicitly which
commands the device supports. All devices are currently treated as
supporting all commands so it just slows everything down. Listing
commands is now fast.
=> Do no requests when listing commands

README.rst, docs/atvremote.rst, pyatv/__main__.py, pyatv/interface.py, pyatv/internal/apple_tv.py, tests/test_interface.py
They no longer work after refactoring commands and help texts. This
makes the code less cluttered and conforms to the public API better.
=> Remove developer commands from atvremote

pyatv/__main__.py
Passing additional arguments to a command, e.g. command=1,2,3 would drop the first argument.
Fixes #99.
=> Fix argument handling in atvremote

pyatv/internal/apple_tv.py, tests/test_functional.py
The intention behind device_id is to generate a unique device ID using the device address. I failed this simple mission by not properly handle the input URL, assuming it was using format ip:port instead of http://ip:port. This resulted in "http" was used as address for all devices. So basically always the same hash. This PR fixes this embarrassing issue...
=> Fix broken device_id

pyatv/__init__.py, pyatv/__main__.py, pyatv/dmap/apple_tv.py, pyatv/mrp/apple_tv.py, tests/test_scan.py
This code is not usable at the moment as an MRP device can never have a
usable service at the moment. But the base code is there to allow for
further implementation.
=> Add base code for MRP

pyatv/dmap/parser.py, pyatv/dmap/tag_definitions.py, pyatv/dmap/tags.py, tests/dmap/test_parser.py
The ceSD tag (unknown name) contains additional metadata about what is
playing. More exactly it contains an id that maps to the media in it's
source service (e.g. if it's a Youtube video it would be a Youtube id).
=> Decode ceSD in DMAP

pyatv/airplay/player.py, tests/fake_apple_tv.py, tests/test_airplay.py
Now NoCredentialsError is raised if a stream is sent to a device that
requires device authentication. Hopefully this makes it more clear what
is going on.
=> Give better error when AirPlay fails

pyatv/pairing.py, tests/fake_apple_tv.py, tests/test_pairing.py
During pairing, pyatv reports back to the Apple TV that it is an iPod.
This is mostly becuase all other libraries out there does that. But for
some reason tvOS will now remove all paired devices with the ipod type
(probably other as well - no tested). But when changed to iPhone
instead, like the iTunes Remote app sends, it sticks like it used to. So
chaning this to make pairing useful again.
=> Use iPhone as device type when pairing

pyatv/pairing.py, tests/test_pairing.py
If a PIN code started with one or more zeros, those zeros would be
dropped and the verifcation would fail. This commit fixes that issue.
=> Handle leading zeros in PIN when pairing

pyatv/dmap/__init__.py, pyatv/interface.py, pyatv/mrp/__init__.py, tests/dmap/test_dmap_functional.py
Experimental suspend support for MRP. It is not supported with DMAP. Should work by running
`atvremote -a --protocol mrp suspend`
=> Suspend support for MRP

pyatv/__init__.py
Filtering was not done for AirPlay, so if for instance MRP results was
requested but an Airplay service was found, scanning would fail.
=> Fix scan bug

examples/manual_connect.py, examples/pairing.py, pyatv/__init__.py, pyatv/__main__.py, pyatv/conf.py, pyatv/dmap/__init__.py, pyatv/exceptions.py, pyatv/mrp/__init__.py, tests/common_functional_tests.py, tests/dmap/test_dmap_functional.py, tests/getmac_stub.py, tests/mrp/test_mrp_functional.py, tests/test_conf.py, tests/test_helpers.py, tests/test_scan.py
This is a breaking change as searching based on address is no longer possible. Device id should be used instead.
Searching looks like this:
```shell
$ atvremote scan
Scan Results
========================================
Name: Vardagsrum
Address: 10.0.10.81
Id: aabbccddeeff 
Services:
- Protocol: AirPlay, Port: 7000
- Protocol: MRP, Port: 49152, Credentials: None
```
And doing something with the device like this:
```shell
$ atvremote -a --id aabbccddeeff playing
Media type: Unknown
Play state: Paused
```
=> Make device searchable by device id

pyatv/mrp/connection.py, pyatv/mrp/messages.py, pyatv/mrp/protocol.py, scripts/autogen_protobuf_extensions.py, scripts/chacha20_decrypt.py, scripts/print_protobuf.py, scripts/proxy.py, tox.ini
This script will mimic an MRP device that you can pair with, using for instance the iOS app. It will then relay messages to a real device, doing re-encryption on the fly so that messages can be intercepted and read in plain text. Usage instructions and caveats are placed as comments in the script.
=> Add proxy MRP script

pyatv/airplay/player.py, tests/airplay/fake_airplay_device.py, tests/airplay/test_airplay.py
This should make it possible to play a URL again.
=> Fix broken play_url in AirPlay

docs/_config.yml, docs/_layouts/template.html, docs/documentation/documentation.md, docs/getting_started.md, docs/index.md, docs/support/faq.md
Did not consider relative links correctly, which broke the links on GitHub since the page is located in a sub directory.
=> Fix relative links in documentation

pyatv/__main__.py
Tiny tiny fix!
Was receiving this error using the example atvremote CLI to pair:
```
root@nuc:/opt/pyatv# atvremote --id 00:11:22:33:44:55 --protocol mrp pair
Enter PIN on screen: 0123
Pairing seems to have succeeded, yey!
ERROR: Pairing failed
Traceback (most recent call last):
File "/usr/local/lib/python3.7/dist-packages/pyatv/__main__.py", line 127, in pair
await self._perform_pairing(pairing)
File "/usr/local/lib/python3.7/dist-packages/pyatv/__main__.py", line 163, in _perform_pairing
pairing.credentials))
AttributeError: 'MrpPairingHandler' object has no attribute 'credentials'
```
It needed an update to reference the correct ```PairingHandler.service.credentials``` attribute.
=> atvremote CLI: fixed credentials reference to .service.credentials

pyatv/mrp/pairing.py
=> Return MRP credentials as string after pairing

pyatv/mrp/pairing.py
Do not send unnecessary messages during init of pairing. Also, closing is not a coroutine.
=> Fix connection handling in MRP pairing

pyatv/__init__.py, pyatv/airplay/__init__.py
This hack creates a new ClientSession every time something is played
with AirPlay. Otherwise the connection will hang, so a spinning wheel
keeps appearing on the screen.
Hopefully this is all that is needed for #266, but it must be verified first.
=> Do not re-use ClientSession for AirPlay

pyatv/mrp/pairing.py
This is a quickfix, I will add better validation of PIN codes later.
Should take care of #291.
=> Support PINs with leading zeros in MRP

docs/development/listeners.md, pyatv/__main__.py, pyatv/dmap/__init__.py, pyatv/interface.py, pyatv/mrp/__init__.py, pyatv/mrp/connection.py, tests/dmap/fake_dmap_atv.py, tests/dmap/test_dmap_functional.py
The new interface (DeviceListener) has two methods:
* connection_lost
* connection_closed
In case of a problem, e.g. server closes connection, connection_lost is called. In case of a controlled shutdown (e.g. user calls close), connection_closed is called instead.
This implementation should be complete for MRP, but I'm not entirely sure with DMAP. There might be situations where I miss a disconnect. But we'll see where it leads.
This is a start in order to support #273.
=> Add interface to report device disconnects

pyatv/__init__.py, pyatv/dmap/pairing.py, tests/zeroconf_stub.py
Seems to cause issues in some setups when IPv6 is disabled. Since I
don't officially support it, this is not really an issue currently.
Fixes #286.
=> Disable IPv6 for now

pyatv/airplay/player.py, pyatv/exceptions.py, tests/airplay/fake_airplay_device.py, tests/airplay/test_airplay.py
This commit will add a similar retry approach to the actual start of playback to how playback status is polled. Hopefully this makes AirPlay streaming more reliable.
=> Add retry attempts when AirPlay streaming fails

docs/documentation/atvremote.md, pyatv/dmap/__init__.py, pyatv/interface.py, pyatv/mrp/__init__.py
Wakes up device from standby. Is not supported by DMAP (but could be simulated via a key press, maybe).
=> Add wakeup command to RemoteControl

.codecov.yml, .travis.yml, README.md, pyatv/__main__.py, pyatv/dmap/__init__.py, pyatv/mrp/srp.py, requirements_test.txt, scripts/setup_dev_env.sh, tox.ini
Switch from coveralls to codecov, enable linting for python 3.8 and clean up tox.
=> Clean up tox and switch from coveralls to codecov

pyatv/__init__.py, pyatv/mrp/player_state.py, pyatv/udns.py
* Do not throw exception when unicast scanning fails
* Log as debug instead of error in udns
* Assume idle playback state if nothing is in playback queue
=> Minor bug fixes

docs/development/scan_pair_and_connect.md, pyatv/__init__.py, pyatv/__main__.py, pyatv/airplay/auth.py, pyatv/airplay/pairing.py, pyatv/airplay/srp.py, pyatv/convert.py, pyatv/exceptions.py, pyatv/mrp/chacha20.py, pyatv/mrp/pairing.py, pyatv/mrp/srp.py, pylintrc, tests/airplay/test_airplay_auth.py, tests/airplay/test_airplay_pair.py, tests/test_convert.py
This begins the journey of cleaning up exceptions thrown during pairing
and authentication. It is not complete, but covers most parts. Will have
to revise later. There are some other bonus fixes as well, mostly
related to naming and consistency.
=> Initial clean-up of pairing and auth exceptions

pyatv/mrp/messages.py, scripts/proxy.py
A new proxy instance is now created for every new client, so it is
possible to connect to the proxy multiple times. Pairing and enabling
of encryption also works as expected now and since the encryption seed
is hardcoded, there is no need to re-pair anymore. Pair once and it
will continue to work even when restarting the script. But no security
whatsoever.
=> Some updates to the MRP proxy

pyatv/__main__.py, pyatv/const.py, pyatv/dmap/__init__.py, pyatv/interface.py, pyatv/mrp/__init__.py, pyatv/mrp/messages.py, pylintrc, tests/common_functional_tests.py, tests/dmap/fake_dmap_atv.py, tests/dmap/test_dmap_functional.py, tests/mrp/fake_mrp_atv.py, tests/mrp/test_mrp_functional.py
Most tests have now been moved to common, mostly some metadata tests
left. This commit fixes the previously broken API for shuffle and
repeat. They now respect the pyatv interface, but MRP implementation
has not yet been tested with real device. So there might be some
integration issues there. Will deal with that later.
Code is quite messy and lots of duplication. I will clean this up soon,
when more things are done.
=> Move more functional tests to common

scripts/proxy.py
All code related to the SRP server has been extracted into its own class
(plus some helper functions). It will soon move into the fake MRP device
so that MRP tests can be written for authentication and pairing.
=> Extract SRP server code in proxy

scripts/proxy.py, tests/airplay/fake_airplay_device.py, tests/dmap/test_dmap_pair.py, tests/mrp/fake_mrp_atv.py, tests/mrp/mrp_server_auth.py, tests/mrp/test_mrp_auth.py, tests/mrp/test_mrp_functional.py, tests/test_atvremote.py
The MRP server auth code now resides with the tests. Proxy is updated.
Also, the MRP fake device has support for authentication and pairing.
Some tests have been added and atvremote tests fixed.
=> Add tests for MRP authentication

pyatv/udns.py, tests/test_udns.py
If a property contained a =, there would be an error.
Fixes #405.
=> Fix bug i TXT handling in UDNS

pyatv/cache.py, pyatv/dmap/__init__.py, pyatv/interface.py, pyatv/mrp/__init__.py, tests/common_functional_tests.py, tests/dmap/fake_dmap_atv.py, tests/dmap/test_dmap_functional.py, tests/mrp/fake_mrp_atv.py, tests/mrp/test_mrp_functional.py, tests/test_cache.py, tests/test_interface.py
This commit adds the following:
* A new method in Metadata called artwork_id, which is a unique
identifier for artwork. In case of MRP, such an identifier already
exists so that identifier is returned. In case of DMAP, this is the
same value as Playing.hash (not ideal but best for now).
* Simple LRU cache in cache.py
* Cache is used together with artwork_id to cache the latest four
artworks that have been fetched.
=> Add simple LRU cache for artwork

pyatv/__main__.py
It's really hard to know how much time things take without any concept
of absolute time in the logs. From now on timestamps will be added if
--debug is used.
=> Add timestamp to debug log in atvremote

pyatv/mrp/__init__.py, pyatv/mrp/player_state.py, tests/mrp/fake_mrp_atv.py, tests/mrp/test_mrp_functional.py
This identifier is certain to be unique as it is generated by the
device. But fallback in case it is not available.
Fixes #327.
=> Use content id as hash in MRP

pyatv/conf.py, tests/test_conf.py
Use this priority for identifier returned by identifier property:
* MRP
* DMAP
* AirPlay
=> Add priority to identifiers in config

scripts/protobuf.py
Move pyatv imports to where they are used, otherwise the script will
fail to run if syntax is incorrect in the wrapper code.
=> protobuf: Move pyatv imports in protobuf.py

docs/development/api_reference.md, pyatv/convert.py, pyatv/dmap/__init__.py, pyatv/dmap/daap.py, pyatv/interface.py, tests/dmap/test_daap.py, tests/test_convert.py, tests/test_interface.py
Move out DMAP related code from convert.py and make what is remaining
part of the public interface.
Fixes #469.
NB: This is not really a breaking change as the convert module has not been a public interface. But someone might still have used it, so will flag it anyway.
=> if: Tidy up convert module and make it public

pyatv/dmap/__init__.py, pyatv/mrp/__init__.py, pyatv/support.py
These functions does not work as intended and are replaced by the power
interface.
Fixes #478.
=> if: Deprecate suspend and wakeup

docs/documentation/documentation.md, pyatv/airplay/srp.py, pyatv/mrp/chacha20.py, pyatv/mrp/srp.py, setup.py, tests/mrp/mrp_server_auth.py
I've managed to remove the need for `curve25519-donna`, `ed25519` and `tlslite-ng` by using crypto routines in `cryptograhy` instead. So from now on, `pyatv` has **three** less dependencies!
=> Remove need for unnecessary crypto libraries

README.md, docs/_config.yml
Just bought `pyatv.dev` because of reasons. So I'm gonna use that for documentation :tada:
=> docs: Change domain to pyatv.dev

docs/api/pyatv/helpers.html, examples/auto_connect.py, pyatv/helpers.py, requirements_test.txt, tests/airplay/test_airplay_pair.py, tests/dmap/test_pairing.py, tests/fake_udns.py, tests/support/test_support.py, tests/support/test_udns.py, tests/test_helpers.py, tests/test_scan.py
Upgrading pytest resulted in all tests using asynctest to break. So I
took the opportunity to rewrite these using pytest instead. So now
asynctest is not needed anymore.
=> test: Migrate from asynctest to pytest-asyncio

pyatv/support/__init__.py, setup.py
The only reason a newer version of protobuf is needed is because of
print_unknown_fields when logging. Check if this flag is supported and
use it if it is, otherwise ignore it so older versions of protobuf can
be used.
=> protobuf: Workaround for older versions

CHANGES.md, docs/api/pyatv/const.html, docs/support/migration.md, pyatv/const.py
Next big release is up packed with updates:
**Changes**
* Add power interface
* Add device information interface
* Add playing app interface
* New scripts: atvscript and atvproxy
* External interface now has type hints
* Pure AirPlay devices are no longer returned by scan
* Files have been moved around and the public interface
is now well-defined
* Documentation has moved to pyatv.dev
**Breaking Changes**
* suspend and wakeup in the remote control interface are now
deprecated. They did not work very well. Use the power interface
instead.
* Black is now used for linting and black does not support
python 3.5, so support for python 3.5 has been dropped.
* helpers.auto_connect is now a coroutine
**Notes**
* Lots of updates to documentation and tests have been made
* An API reference is now …
=> Release 0.5.0

scripts/fake_device.py, tests/airplay/fake_airplay_device.py, tests/airplay/test_airplay.py, tests/airplay/test_airplay_auth.py, tests/airplay/test_airplay_pair.py, tests/dmap/fake_dmap_atv.py, tests/dmap/test_dmap_functional.py, tests/dmap/test_dmap_pair.py, tests/mrp/fake_mrp_atv.py, tests/mrp/test_mrp_auth.py, tests/mrp/test_mrp_functional.py, tests/scripts/script_env.py
This script will set up a fake device called FakeMRP at localhost. It
will be in idle state, but supports pairing and all commands that the
fake device implements. Most things are just logged so nothing really
happens.
A new instance is created for each connection to make sure encryption
works properly. Verified to work with the Home Assistant component.
Start of #518. I will write a page in the developer documentation about this.
=> Add start of fake device script

pyatv/mrp/__init__.py, tests/fake_device/mrp.py, tests/mrp/test_mrp_functional.py
If neither artworkIdentifier or contentIdentifier are present, fall back
to queue identifier.
Fixes #550.
=> mrp: Handle artwork without identifier

pyatv/scripts/atvscript.py
Output-flushing is required to avoid buffering between processes.
Without flush, client application only receive the output from atvscript
when either a bigger amount of output is generated or the application
terminates.
This is the same as #547 which seems to have a lot of problems with GitHub Actions for some reason.
=> atvscript: Flush output of each line

scripts/release.py
Instead of basing the release branch of master, use the current commit
as the simplifies when creating minor releases.
=> release: Use current commit instead of master

scripts/api.py, scripts/release.py
* Do not use single quotes as black prefers double quotes
* Re-generate API documentation since const.py is changed
=> release: Adapt script to recent changes

tox.ini
Avoid packaging and installing pyatv every time something is run. This
change alone cuts runtime by around 50%. Also some other minor fixes.
=> cq: Improvements to tox

docs/api/pyatv/const.html, docs/api/pyatv/interface.html, docs/documentation/atvremote.md, pyatv/const.py, pyatv/dmap/__init__.py, pyatv/interface.py, pyatv/mrp/__init__.py, pyatv/mrp/messages.py, tests/dmap/test_dmap_functional.py, tests/fake_device/mrp.py, tests/mrp/test_mrp_functional.py
These functions will skip forward or backwards a short time period. For `MRP` this period is defined by the running application, but is typically 10-30 seconds. `DMAP` does not natively support this but has simulated functions that retrieves current position and changes it using `set_position`. In this case it's hard coded to ten seconds.
It is currently not possible to specify skip interval manually, that is a future improvement (#472).
Fixes #345.
=> Add support for skip_forward and skip_backward

docs/api/pyatv/interface.html, docs/support/troubleshooting.md, pyatv/dmap/__init__.py, pyatv/interface.py, pyatv/mrp/__init__.py, pyatv/mrp/player_state.py, pyatv/scripts/atvremote.py, tests/common_functional_tests.py, tests/dmap/test_dmap_functional.py
Unify the listener implementations under a common pattern and store
references to listeners as weak references. It should never be the case
that pyatv objects are kept alive because the listeners were never unset
properly.
=> if: Use weak references for listeners

pyatv/mrp/__init__.py, tests/common_functional_tests.py, tests/dmap/test_dmap_functional.py
No tests are present for this yet as I need to re-work the button
handling quite a bit (same situation as for home_hold). Will leave that
for later.
This will take care of #522 once pyatv has been bumped in the HA component.
=> mrp: Change topmenu to go to main menu

docs/api/pyatv.html, docs/api/pyatv/exceptions.html, docs/documentation/concepts.md, pyatv/__init__.py, pyatv/exceptions.py, pyatv/scripts/__init__.py, pyatv/scripts/atvremote.py, pyatv/scripts/atvscript.py, pyatv/support/udns.py, tests/support/test_udns.py
Unicast scanning only works when the target address is in the same
subnet as the host. Now an exception is raised if unicast scanning is
performed on an address outside of any local subnet.
Fixes #581.
=> udns: Verify address in any local subnet

docs/api/pyatv.html, pyatv/__init__.py, tests/test_scan.py
I messed up typing a bit when implementing support for streaming local
files with AirPlay, so play_url stopped working. This should fix that
problem.
=> scan: Fix type bug in scan_hosts

docs/api/pyatv/interface.html, pyatv/mrp/connection.py
MrpConnection and MrpProtocol depends on each other because, so a weak
reference should be used to be more helpful to the garbage collector.
=> mrp: Make connection listener into weakref

pyatv/support/udns.py, tests/conftest.py, tests/fake_udns.py, tests/support/test_udns.py
From now on the UDNS request will be resent every second until timeout
is reached. This should help when sending to a device that is waking up.
Relates to #595.
=> udns: Send UDNS request every second

pyatv/scripts/atvscript.py
Add a line that is printed when the script is started to make it easier
to separate different runs because of append mode.
=> atvscript: Add start log entry

pyatv/mrp/__init__.py, pyatv/mrp/pairing.py, pyatv/mrp/protocol.py, pyatv/scripts/atvproxy.py, pyatv/support/udns.py, tests/mrp/test_mrp_auth.py, tests/support/test_support.py
This fixes all warnings provided by pytest that is within pyatv.
Remaining warnings come from dependencies.
=> cq: Fix warnings from tests

docs/api/pyatv/interface.html, docs/development/features.md, pyatv/interface.py, pyatv/mrp/__init__.py, tests/common_functional_tests.py, tests/dmap/test_dmap_functional.py, tests/mrp/test_mrp_functional.py, tests/test_interface.py
If the "play_pause" feature isn't supported by the running app, emulate
it by sending play or pause depending on device state.
Fixes #597.
=> mrp: Add fallback for play_pause

docs/api/pyatv/interface.html, docs/development/metadata.md, docs/documentation/atvremote.md, pyatv/dmap/__init__.py, pyatv/interface.py, pyatv/mrp/__init__.py, pyatv/scripts/atvremote.py, tests/common_functional_tests.py, tests/dmap/test_dmap_functional.py, tests/fake_device/dmap.py, tests/fake_device/mrp.py, tests/mrp/test_mrp_functional.py
This adds `width` and `height` to the `artwork` method so that artwork of arbitrary sizes can be requested. In the end, this is just a request and the device can return artwork with any size. For MRP the correct size is returned. DMAP does not support this yet.
=> Support for retrieving artwork of arbitrary size

CHANGES.md, docs/api/pyatv/const.html, docs/support/migration.md, pyatv/const.py
*Changes:*
* Stream local files via AirPlay
* Unicast scanning will now wake up sleeping devices automatically
* Support for skip_forward and skip_backward
* Support volume_up and volume_down (DMAP)
* Artwork can be retrieved with custom width and height
* top_menu now goes to main menu on tvOS
* play_pause will be emulated by play/pause on tvOS if not natively supported
* Fix retrieval of artwork with missing identifier
* Many improvements to atvscript (timestamp, exception handling, etc.)
*Notes:*
* Default timeout for HTTP requests (DMAP and AirPlay) has been increased to
25 seconds to deal with waking up devices
* Weak references are now used for all listeners, see
https://pyatv.dev/support/troubleshooting if you have any problems
* Unicast scanning for hosts outside of any local …
=> Release 0.6.0

.github/workflows/tests.yml, base_versions.txt, docs/documentation/documentation.md, setup.py, tox.ini
This will run all tests on python 3.8 (with Github Actions) with the
lowest supported version of all depdendencies. I have bumped a few
versions so that it actually works...
Fixes #627.
=> cq: Run tests with base versions

docs/documentation/atvproxy.md, pyatv/scripts/__init__.py, pyatv/scripts/atvproxy.py
Tunnel support allows publishing of arbitrary zeroconf service and
relaying of data between hosts for easy interception. A limitation is
currently that atvproxy will have to be restarted between each connect.
This shall be fixed later.
=> atvproxy: Add tunnel support

pyproject.toml
These directories seems to cause a lot of problems when running in
Github Actions. This is an attempt to improve stability.
=> cq: Exclude __pycache__ from black

docs/documentation/atvproxy.md, pyatv/scripts/atvproxy.py
Only credentials and Apple TV IP address needs to be provided now. Old
behavior is still supported via options.
Fixes #693.
=> atvproxy: Simplify MRP usage

docs/api/pyatv.html, docs/api/pyatv/conf.html, docs/api/pyatv/interface.html, pyatv/__init__.py, pyatv/conf.py, pyatv/interface.py, pyatv/support/udns.py, tests/fake_udns.py, tests/support/dns_utils.py, tests/support/test_udns.py, tests/test_scan.py
Add better service parsing to mdns implantation and perform unicast scanning if result is sent from a sleep proxy.
=> Support sleep proxies with new scanning

docs/api/pyatv/const.html, docs/api/pyatv/interface.html, docs/development/control.md, docs/index.md, pyatv/const.py, pyatv/dmap/__init__.py, pyatv/interface.py, pyatv/mrp/__init__.py, pyatv/scripts/atvremote.py, tests/common_functional_tests.py, tests/dmap/test_dmap_functional.py, tests/fake_device/dmap.py, tests/fake_device/mrp.py, tests/mrp/test_mrp_functional.py, tests/utils.py
This PR makes it possible to perform different actions for some buttons, e.g. long pressing menu or double tapping home. It also reverts the behavior in #579 for the `topmenu` button to make that more usable.
=> Add support for button actions

pyatv/mrp/protobuf/ContentItem.proto, pyatv/mrp/protobuf/ContentItem_pb2.py, pyatv/mrp/protobuf/ContentItem_pb2.pyi, pyatv/mrp/protobuf/__init__.py
From experimentation, the format of the `availableLanguageOptions` and `currentLanguageOptions` fields in the `ContentItem` protobuf are slightly different.
This introduces a new protobuf `LanguageOptionList` to try and capture the correct format for the `availableLanguageOptions` field.
This should pave the way to better understanding these fields. I'll open up an issue later with some documentation on the `EnableLanguageOption`/`DisableLanguageOption` command. The payload for that command is actually the marshal object for the `LanguageOption` run through `NSKeyedArchiver`. Go figure 🤷
=> mrp: Update protobuf for language options.

base_versions.txt, docs/development/scan_pair_and_connect.md, docs/documentation/documentation.md, docs/support/scanning_issues.md, pyatv/dmap/pairing.py, pyatv/scripts/__init__.py, pyatv/scripts/atvproxy.py, pyatv/support/mdns.py, scripts/fake_device.py, tests/dmap/test_dmap_functional.py, tests/dmap/test_pairing.py, tests/fake_device/dmap.py, tests/zeroconf_stub.py
As aiozeroconf causes problems (due to bugs) and is not maintained
anymore, it's better to move back to zeroconf again. Since service
discovery is already done by pyatv, only service publishing is really
used.
Relates to #750.
=> scan: Migrate back to zeroconf from aiozeroconf

pyatv/mrp/messages.py
The connection sometimes seems to hang after artwork has been received.
Reason is still unknown, but this change seems to make it work better.
It comes with the price that if artwork is large (file size), the
artwork might only be delivered as a transaction. Since transactions are
not implemented yet, artwork will fail in these cases.
Relates to #609.
=> mrp: Potential fix for protocol hangs

pyatv/mrp/__init__.py
I'm not sure if this will cause a regression but it solves the performance issue.
Resolves #773 
Before this change the event loop was taking 13% of the recording time.  
https://maui.koston.org:8123/local/ec.svg
After its below the measurable threshold.
https://maui.koston.org:8123/local/ec3.svg
=> Resolve performance slowdown with copying playing data

docs/api/pyatv/conf.html, pyatv/conf.py, tests/dmap/test_dmap_functional.py, tests/scripts/script_env.py, tests/test_conf.py
=> Fix invalid DMAP identifier when name collision exists on the network

CHANGES.md, docs/api/pyatv/const.html, pyatv/const.py
*Changes:*
* PIN code screen for MRP will now disappear after pairing
* Less and more compact debug logs in mdns and knock
*All changes:*
```
9f1d1d0 mrp: Verify credentials after pairing
1d799f2 cq: Minor clean ups and fixes
061add1 build(deps): bump codecov from 2.1.9 to 2.1.10
dc31ac9 build(deps-dev): bump tox from 3.20.0 to 3.20.1
```
=> Release 0.7.4

setup.py
otherwise it tries to install a package called `examples` at top level, which is forbidden:
```
...
no previously-included directories found matching 'docs/_site'
no previously-included directories found matching 'docs/.sass-cache'
writing manifest file 'pyatv.egg-info/SOURCES.txt'
Copying pyatv.egg-info to /var/tmp/portage/dev-python/pyatv-0.7.4/image/_python3.8/usr/lib/python3.8/site-packages/pyatv-0.7.4-py3.8.egg-info
running install_scripts
Installing atvproxy script to /var/tmp/portage/dev-python/pyatv-0.7.4/image/_python3.8/usr/lib/python-exec/python3.8
Installing atvremote script to /var/tmp/portage/dev-python/pyatv-0.7.4/image/_python3.8/usr/lib/python-exec/python3.8
Installing atvscript script to /var/tmp/portage/dev-python/pyatv-0.7.4/image/_python3.8/usr/lib/python-exec/python3. …
```
=> Update setup.py, extend exclude mask

MANIFEST.in
otherwise the SDIST from Pypi is not compilable, because base_versions.txt (which is read by setup.py) would be missing.
=> update MANIFEST.in, add missing file

CHANGES.md, docs/api/pyatv/const.html, pyatv/const.py
*Changes:*
* Revert to use random source port for MDNS
* Fix "Received UpdateClientMessage for unknown player xxx""
*All changes:*
```
cd6d53f mdns: Revert binding to port 5353
a394b52 mrp: Handle UpdateClient before SetState
a3d46d3 build(deps): bump mypy from 0.782 to 0.790
c648eaa update MANIFEST.in, add missing file
162f319 build(deps): bump pytest from 6.1.1 to 6.1.2
f1a7223 build(deps): bump pdoc3 from 0.9.1 to 0.9.2
0b97aab build(deps): bump codespell from 1.17.1 to 2.0.0
795aaa7 Update setup.py, extend exclude mask
5e27bc7 gha: Fix python 3.9 and use env files
```
=> Release 0.7.5

pyatv/support/net.py, tests/support/test_net.py
This should allow using keepalive on platforms that have the appropriate constants available within Python, as well as Darwin. The main personal driver for this was to silence the warning (and actually implementing keepalive support) on FreeBSD, which should address #836. I also added a couple of tests for the `tcp_keepailve()` function.
=> Use TCP keepalive on more platforms

base_versions.txt
This was triggered by protobuf having release 4.0.0-rc2, and then
abandoning the idea of a 4.0 release. There have been a few releases
since then, and 4.0 is spewing warning messages.
=> Slightly refine protobuf and srptools base requirements

CHANGES.md, docs/api/pyatv/const.html, pyatv/const.py
*Changes:*
* DNS parsing has been re-written which should be more stable
and handle more use cases
* TCP keep-alive has been added to more platforms, FreeBSD being one of them
* Player management has been totally re-written for MRP, so hopefully
play state should be more accurate now
* A delay has been added to turn\_off (MRP), so it should work again
* A heartbeat loop has been added that sends a "heartbeat" to the device
every 30s to detect connection problems
* Protobuf definitions have been further lifted to match later tvOS versions
*Notes:*
* Fixed a bug where Playing instancess were not immutable
* Push updates are only issued when something in the Playing instance changed.
Previously, unrelated changes to the device could trigger push updates with
the same content in Playing.
*All …
=> Release 0.7.6

.github/workflows/log.yaml
When using the following syntax to add logs in an issue:
~~~
```log
log goes here
```
~~~
A workflow will be triggered that generates an html log, commits it to a
branch and posts a new comment in the issue with a link to the file.
It works with new issues, comments and edits to existing comments.
=> gha: Generate html logs for logs in issues

.github/workflows/log.yaml, scripts/log2html.py
It seems like onload does not work reliably with htmlpreview, so now a
polling loop looking for the element used for displaying log entries
is used instead. Not so pretty but works for now.
A workaround, storing the issue/comment body in a file instead of
passsing via environment variable has also been introduced. Storing too
large payloads in an environment variable seemed to throw an error.
=> log2html: Fix broken log entry loading

.github/workflows/log.yaml
To circumvent a lot of problems getting the issue/ comment body used
for log extraction, use the API (via pygithub) to save the body instead.
That takes care of all potential problems with sizes and unescaped characters.
=> gha: Save log for log2html using pygithub

CHANGES.md, docs/api/pyatv/const.html, pyatv/const.py
*Changes:*
* Fix bug where apps would appear to crash on tvOS 14.5 (beta)
* Add a retry to heartbeat loop
* Add new script that parses logs: atvlog
*All changes:*
```
60df163 mrp: Use GenericMessage for heartbeats (#975)
8df084f support: Convert knock to use asyncio (#988)
14196da gh: Add example to attach log to a bug report (#984)
dbe734c build(deps-dev): bump tox from 3.22.0 to 3.23.0
1e1922e cq: Run pylint from tox (#979)
7464cb7 atvlog: Rename log2html and bundle it (#982)
34d2f53 log2html: Add separate include and exclude filters (#981)
0a6fa5e log2html: Add generation date and command (#980)
7184717 mrp: Add retry to heartbeats (#978)
b0eaaef log2html: Allow toggling of showing date (#974)
adda918 build(deps): bump mypy from 0.800 to 0.812
fa8b05d gha: Save log for log2html using …
```
=> Release 0.7.7

docs/api/pyatv/exceptions.html, pyatv/exceptions.py, pyatv/mrp/protocol.py
Resolves #1007
- Cleans up old connection by calling ```stop()``` before establishing a new connection
- Prevents unintentionally ```start()```ing a new connection after ```stop()```ing
- Prevents multiple parallel ```connect()``` calls
=> Improve handling of unreliable connections

pyatv/mrp/protobuf/CryptoPairingMessage.proto, pyatv/mrp/protobuf/CryptoPairingMessage_pb2.py
Turns out the types of this message aren't `required`. Here's an example of a message without `pairingData` (generated by sending an incorrectly encrypted TLV during pairing):
```
type: CRYPTO_PAIRING_MESSAGE
errorCode: NoError
[cryptoPairingMessage] {
status: -6754
isRetrying: false
isUsingSystemPairing: false
state: 0
}
uniqueIdentifier: "A6FBC494-2C5A-4B54-8617-2D8DD5DD1CD6"
```
See also #1010
=> chore: update types in CryptoPairingMessage to be optional

pyatv/support/knock.py
It is normal that the task gets cancelled when a connection has been
made to a device, so this is expected to happen.
=> knock: Suppress CancelledError exception

.gitpod.yml, README.md
It's not possible to use DockerInDocker, so the build_docs.sh script
won't work. I need to create my own Dockerfile with Jekyll in it and
run without Docker.
Add a GitPod badge to README as well.
=> env: Remove documentation tab from GitPod for now

docs/api/pyatv/interface.html, pyatv/dmap/__init__.py, pyatv/interface.py, pyatv/mrp/__init__.py, tests/fake_device/mrp.py, tests/mrp/test_mrp_functional.py
=> mrp: Handle missing artwork gracefully

docs/api/pyatv.html, docs/api/pyatv/interface.html, pyatv/__init__.py, pyatv/airplay/__init__.py, pyatv/companion/__init__.py, pyatv/dmap/__init__.py, pyatv/mrp/__init__.py, pyatv/raop/__init__.py, pyatv/scripts/atvproxy.py, pyatv/support/facade.py, tests/companion/test_companion_functional.py, tests/fake_device/companion.py, tests/support/test_facade.py
These methods will now have priority over MRP if both are present. To
make that work, Companion will not be set up if no credentials are
present. Otherwise it would be problematic to connect using a config
obtained via scanning without filling in Companion credentials.
Relates to #1051
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/1104"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> companion: Add support for turn_on and turn_off

pyatv/mrp/player_state.py
Deep copies should not be needed anymore since no player state is stored
long-term. This will save a lot of CPU cycles.
Fixes #1038
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/1105"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> mrp: Do not deep copy protobuf messages

pyatv/dmap/__init__.py, pyatv/mrp/__init__.py, pyatv/mrp/protocol.py, pyatv/raop/raop.py, pyatv/scripts/atvproxy.py, pyatv/support/knock.py, pyatv/support/mdns.py
This commit makes sure futures are properly cancelled and not laying
around after closing connection to a device.
Relates to #1123
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/1124"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> cq: Clean up usage of ensure_future

docs/api/pyatv/conf.html, docs/api/pyatv/helpers.html, pyatv/conf.py, pyatv/helpers.py, pyatv/support/scan.py, tests/support/test_scan.py, tests/test_conf.py, tests/test_helpers.py
This helper can extract a unique identifier from a Zerconf service in
the same way as pyatv does internally. It is meant to be used when
Zeroconf service data comes from elsewhere than when scanning in pyatv,
e.g. when using python-zeroconf manually.
Relates to #1127
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/1143"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> helpers: Add get_unique_id

docs/documentation/supported_features.md, pyatv/raop/__init__.py
If no RAOP credentials are provided, use the ones from AirPlay if they
are present. It's the same credentials in the end.
Relates to #1078
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/1146"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> raop: Fallback to AirPlay credentials

scripts/setup_dev_env.sh
This flag is set to true in GitPod, which breaks pip install. So unset
it for now.
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/1150"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> scripts: Unset PIP_USER in setup_dev_env.sh

CHANGES.md, docs/api/pyatv/const.html, pyatv/const.py
Here comes a new release, filled to the brim with new stuff! First and foremost, it
introduces support for not one but *two* new protocols: Companion and RAOP. The
Companion protocol is used to list and launch apps installed on an Apple TV as well
improving power management support. RAOP adds support for proper audio streaming
to AirPlay receivers. Both protocols are still early in development and may contains a
few bugs (yeah...). You will likely see new features added to these over time.
A big new change in this release, that isn't really noticeable at first, is a new layer
that relays calls between public interface methods and underlying protocols. What does
this mean then? Well, we have the public interfaces (Metadata, RemoteControl. etc.)
and the protocols implementing them (DMAP, …
=> Release 0.8.0

pyatv/raop/__init__.py, pyatv/raop/raop.py, pyatv/raop/timing.py
The implementation of monotonic on Windows has very low resolution, so
streaming doesn't work. So switch to perf_counter as it has much higher
resolution. On all platforms except for Windows, these function are
exactly the same.
Relates to #1169
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/1171"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> raop: Use perf_counter instead of monotonic

CHANGES.md, docs/api/pyatv/const.html, pyatv/const.py
This minor release contains a few improvements to the RAOP protocol.
First and foremost, `time.perf_counter` is now used in favor of
`time.monotonic` for audio scheduling. Scheduling has also been changed to work
with "global time" (from stream start) instead of per frame. These changes
improve streaming stability, with less chance of getting out of sync. They were
also necessary to get streaming working on Windows.
Another important addition in the streaming department is the ability to read
input from a FILE-like object, instead of just from a filename. One usecase for
this is to take input via stdin from another process and send it to a receiver.
`atvremote` has been adjusted to read from stdin if `-` is specified as
filename. Here's an example streaming output from ffmpeg (RTSP as …
=> Release 0.8.1

.github/workflows/tests.yml, tox.ini
I don't know for sure if this fixes or even improves the situation, but I'll give it a try for a while and see.
Relates to #1174
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/1175"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> gha: Re-run tox without cache if failure

.github/workflows/tests.yml, scripts/tox.sh
It was not possible to set an environment variable mid-command:
tox ... || SOME_ENV tox ...
So the command has moved to a script now.
Relates to #1174
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/1180"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> gha: Another attempt to re-run tox on failure

.github/workflows/tests.yml
Seems like the tox script is not executed properly on Windows, so tests
are not executed there.
Relates to #1174
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/1199"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> gha: Fix running tox on Windows

pyatv/support/scan.py
Relates to #1194
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/1200"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> debug: Include zeroconf properties in debug log

docs/api/pyatv.html, docs/api/pyatv/conf.html, docs/internals/design.md, pyatv/__init__.py, pyatv/airplay/__init__.py, pyatv/companion/__init__.py, pyatv/conf.py, pyatv/dmap/__init__.py, pyatv/mrp/__init__.py, pyatv/raop/__init__.py, pyatv/support/scan.py, tests/airplay/test_airplay.py, tests/airplay/test_airplay_scan.py, tests/companion/test_companion.py, tests/companion/test_companion_scan.py, tests/conftest.py, tests/dmap/test_dmap.py, tests/dmap/test_dmap_scan.py, tests/mrp/test_mrp.py, tests/mrp/test_mrp_scan.py, tests/raop/test_raop.py, tests/raop/test_raop_scan.py, tests/support/test_mdns_functional.py, tests/support/test_scan.py, tests/test_conf.py, tests/test_scan_functional.py, tests/utils.py
This commit moves scan related code out to the protocols by letting
protocols procvide which zeroconf services they need as well as handlers
for found services. Functional tests have also been pushed back to the
protocols, making the "core" fairly protocol agnostic.
Relates to #1202
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/1207"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> scan: Move scan code to protocols

tests/support/test_mdns_functional.py, tox.ini
In some peculiar cases pdoc3 generates different output depending on
which python version it is run with. Just settle with one version to
circumvent errors on CI runs.
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/1216"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> env: Only verify docs with py3.8

docs/api/pyatv.html, docs/development/scan_pair_and_connect.md, docs/documentation/atvremote.md, pyatv/__init__.py, pyatv/scripts/__init__.py, pyatv/scripts/atvremote.py, pyatv/support/scan.py, tests/companion/test_companion_scan.py, tests/conftest.py, tests/test_scan_functional.py
This commit is two-fold:
* It allows "protocol" passed to scan to either be a single protocol or
a set of protocols
* Only the specified protocols will be added to configurations of found
devices, even if they support additional protocols
The intention here is to support scanning only for the protocols of
interest, e.g. to ignore a protocol. The --scan-protocols option has
been added to atvremote to support this.
Relates to #1211
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/1213"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> scan: Support scanning for specific protocols

docs/api/pyatv/helpers.html, docs/documentation/supported_features.md, pyatv/dmap/__init__.py, pyatv/dmap/tag_definitions.py, pyatv/helpers.py, tests/dmap/test_dmap.py, tests/dmap/test_dmap_scan.py, tests/fake_udns.py, tests/test_helpers.py, tox.ini
This commit adds support for the HSCP service used by the Music app (on
macOS). It's exactly the same as DMAP with Home Sharing, just a few
different zeroconf properties.
Relates to #1172
Not entirely ready yet as documentation is needed and I also need to decide what the device info API should return.
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/1182"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> dmap: Add support for HSCP service

docs/api/pyatv/interface.html, docs/documentation/supported_features.md, pyatv/companion/__init__.py, tests/companion/conftest.py, tests/companion/test_companion_functional.py, tests/fake_device/companion.py
WIP
Adds support for a few buttons. Still haven't found any equivalent to the remaining buttons.
Still missing tests and documentation.
Relates to #1190
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/1218"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> companion: Add support for several buttons

pyatv/support/mdns.py, pyatv/support/scan.py, tests/fake_udns.py, tests/support/test_mdns.py, tests/support/test_mdns_functional.py, tests/support/test_scan.py
This PR aims to fix #1234 by splitting requests over several messages (instead of just one). So far only unicast scanning has been (partially implemented).#1218 
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/1235"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Send MDNS service requests over several messages

CHANGES.md, pyatv/const.py
Time for another minor release! Highlights this time is
improved scanning, password protected RAOP services, support
for HSCP and some remote buttons in Companion.
An issue hwere some devices were not discovered by Home Assistant
anymore suddenly appeared (pun intended). Some digging concluded
that asking for too many Zeroconf services in one request might
yield a response too big to fit in one IP packet. This makes the
sender silently drop records, rendering the response incomplete
without pyatv knowing that. Since Companion and RAOP was added in
0.8.0 (which require three new services in total), that was the
tipping point. From now on, pyatv will spread services over a few
requests to work around this issue.
It is now possible to stream audio to password protected AirPlay
receivers …
=> Release 0.8.2

pyatv/mrp/connection.py
Temporary fix due to StateProducer not supporting type hints.
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/1251"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> mrp: Disable some type checking

docs/api/pyatv.html, docs/api/pyatv/interface.html, pyatv/airplay/__init__.py, pyatv/companion/__init__.py, pyatv/dmap/__init__.py, pyatv/interface.py, pyatv/mrp/__init__.py, pyatv/raop/__init__.py, pyatv/support/facade.py, tests/conftest.py, tests/support/test_facade.py
This change allows protocols to return tasks that have not finished yet.
When closing a device, all of these tasks are returned so the user can
manually wait for them to finish if desired.
Relates to #1109
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/1267"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> facade: Return remaining tasks in close

README.md
The logo is broken on external sites, like pypi. So lets use an absolute
address to fix that.
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/1272"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> docs: Use absolute address to logo in README

base_versions.txt, pyatv/raop/__init__.py, pyatv/raop/audio_source.py, pyatv/raop/metadata.py
This will fix the dependency issues that audio-metadata provides since mediafile only has mutagen as dependency (which has no other dependencies). Current problem is that mediafile doesn't support WAV-files yet (I opened an issue about it https://github.com/beetbox/mediafile/issues/49 and a PR https://github.com/beetbox/mediafile/issues/50), so will have to wait until that is fixed.
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/1271"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> core: Switch from audio-metadata to mediafile

pyatv/core/facade.py, pyatv/protocols/airplay/__init__.py, pyatv/protocols/airplay/auth/__init__.py, pyatv/protocols/airplay/features.py, pyatv/protocols/airplay/pairing.py, pyatv/protocols/raop/__init__.py, tests/common_functional_tests.py, tests/conftest.py, tests/core/test_facade.py, tests/fake_udns.py, tests/protocols/airplay/test_airplay_interface.py, tests/protocols/airplay/test_features.py, tests/protocols/dmap/test_dmap_functional.py, tests/protocols/mrp/test_mrp_functional.py
Base feature availability of `play_url` from feature flag in zeroconf. Also raise exception if call is made to `play_url` when it's not supported.
Fixes #1308
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/1310"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> airplay: Improve feature availability support and error handling

CHANGES.md, README.md, docs/support/migration.md, pyatv/const.py, tests/protocols/raop/test_raop_functional.py
So, what's new? Yeah, right, tvOS 15 was released the day before yesterday
which broke everything. My intention was to release 0.9.0 before tvOS 15
dropped, but things kept popping up and I had no choice but to delay. So here
we are.
The biggest feature in this release is obviously support for tvOS 15. Perhaps
not the most exciting feature per se, but important as most of the
functionality in pyatv is lost without it. The gist is that Apple decided to
drop support for the MRP protocol introduced in tvOS. In practice they didn't
get rid or it, they just allocated a special stream type in AirPlay (2) and
decided to tunnel MRP over it. So MRP is still there, it's just carried over
AirPlay now. As far as I know, this is how they have done it the last couple of
iOS/tvOS releases. So it's not …
=> Release 0.9.0

docs/api/pyatv.html, pyatv/__init__.py
Instead of connecting to protocols based on the order they were
discovered, use a pre-defined order (protocol name). It seems some Apple
TVs upgraded to tvOS 15 gets a lingering MRP service not possible to
connect to. If the MRP service is discovered prior to AirPlay,
connecting to such a device will fail. Maintaining this particular order
will serve as a work-around for that.
Relates to #1322
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/1328"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> core: Use connect order based on protocol

pyatv/protocols/airplay/__init__.py, pyatv/protocols/companion/__init__.py, pyatv/protocols/raop/__init__.py, stream.py, tests/protocols/airplay/test_airplay.py, tests/protocols/companion/test_companion.py, tests/protocols/raop/test_raop.py
See #1330 for details. HomePods will now always be marked as `Unsupported` as pyatv does not support pairing with them anyways.
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/1331"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Improve pairing requirements in RAOP and Companion

.github/workflows/release.yml, CHANGES.md, pyatv/const.py
Minor bug fix release coming up! Should fix connection issues when a stale
MRP service is present after upgrading to tvOS 15. Also improves pairing requirement
handling for AirPlay and RAOP in case access control is set to "Only devices in
my home" (will now report as Disabled). Companion is also reported as Unsupported
for HomePods as pyatv cannot pair with them.
A new convert method to convert a `DeviceModel` to string has been added.
**Changes:**
*Protocol: AirPlay:*
```
2558a89 airplay: Support Disabled pairing requirement
```
*Protocol: Companion:*
```
6cb7269 companion: Better support for pairing requirement
```
```
d257378 raop: Support Disabled pairing requirement
```
*Other:*
```
70b4992 convert: Add model_str method
535b56b core: Use connect order based on …
```
=> Release 0.9.1

pyatv/protocols/mrp/__init__.py, tests/fake_device/mrp.py, tests/protocols/mrp/test_mrp_functional.py, tests/protocols/mrp/test_mrp_interface.py
Use outputDeviceUID from the latest VolumeControlCapabilitiesDidChange
message instead of deviceUID from DeviceInfoMessage. I'm not entirely
sure how this is supposed to work, but should handle grouped players
(which current implementation does not).
Relates to #1298
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/1327"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> mrp: Updates to volume management

docs/api/pyatv/interface.html, pyatv/interface.py, pyatv/protocols/airplay/__init__.py, pyatv/protocols/companion/__init__.py, pyatv/protocols/mrp/__init__.py, pyatv/protocols/raop/__init__.py, tests/fake_device/mrp.py, tests/protocols/airplay/test_airplay.py, tests/protocols/companion/test_companion.py, tests/protocols/mrp/test_mrp_functional.py, tests/protocols/raop/test_raop.py, tests/test_interface.py
Add a raw_model field to DeviceInfo that contains an opaque model
description as a string. This string is device and protocol specific.
Relates to #1343
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/1346"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> core: Add raw_model to DeviceInfo

pyatv/protocols/dmap/pairing.py, tests/protocols/companion/test_companion.py
Enable a test that was commented by accident and don't create unnecessary  instances of `Zeroconf`.
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/1347"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Some minor fixes

.github/workflows/release.yml, CHANGES.md, pyatv/const.py
What? Another release? Already? Suure... So, I am integrating pyatv 0.9.x with
Home Assistant and I find these small annoyances or missing pieces along the way,
fixing them one by one as I go. This release is thus a micro-update, but it
contains a few nuggets.
A `Music` device model has been added that represents the Music app/iTunes. In
the same department I've added a property called `raw_model` to `DeviceInfo`,
returning a raw model string in case it's not a model known by pyatv. This is
very useful for AirPlay receivers as `raw_model` will usually contain the device
manufacturer and hardware model.
It is now possible to pass a set of identifiers to `pyatv.scan`. The intended
use case is to pass all identifiers belonging to a device to handle cases where a
service is missing or getting …
=> Release 0.9.2

.github/workflows/tests.yml, chickn.yaml
Always rebuild miniaudio when running with GitHub Actions as that seems
to improve stability.
Relates to #1437
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/1444"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> env: Rebuild miniaudio in tests workflow

docs/api/pyatv.html, docs/api/pyatv/conf.html, docs/api/pyatv/interface.html, pyatv/__init__.py, pyatv/conf.py, pyatv/core/__init__.py, pyatv/interface.py, tests/common_functional_tests.py, tests/protocols/raop/test_raop_functional.py
This is a first step towards making configurations immutable, so that the config passed to `pyatv.connect` can't be modified externally. The "main service" still leaks and should be immutable as well, but will handle that separately.
Fixes #1414
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/1445"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> core: Make config immutable

docs/documentation/protocols.md
Clarify how messages are encoded on the AirPlay data channel.
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/1481"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> docs: Clarifications for data channel payload

docs/api/pyatv.html, docs/api/pyatv/conf.html, docs/api/pyatv/interface.html, docs/development/scan_pair_and_connect.md, pyatv/__init__.py, pyatv/conf.py, pyatv/core/__init__.py, pyatv/interface.py, pyatv/protocols/airplay/__init__.py, pyatv/protocols/mrp/__init__.py, tests/test_conf.py, tests/test_scan_functional.py
Services can now be disabled, which prevents pyatv from connecting to
them. This allows pyatv to collect device info from such services,
without connecting to them.
Relates to #1492
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/1493"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> core: Add enabled state to services

CHANGES.md, docs/documentation/supported_features.md, docs/support/migration.md, pyatv/const.py
It's already Decemeber, how did that happen? Not sure... Anyways, I've
prepared a small update with few neat things:
* Implemented a missing type in OPACK that raised an exception when
connecting to Companion for some people (`TypeError: 0xc0`)
* More buttons are supported by Companion as we as proper feature reporting
for some of them
* A persistent connection is now set up to Companion. The active device listener
is called if connection is lost.
* A copy is now made of the configuration passed to `pyatv.connect` which
means a config cannot be modified after connecting anymore
* Experimental support for streaming via HTTP(S) has been added to `stream_file`
**Changes:**
*Protocol: MRP:*
```
f6a8973 mrp: Migrate protocol to MessageDispatcher
```
*Protocol: Companion:*
```
dd44437 …
```
=> Release 0.9.7

docs/api/pyatv.html, docs/api/pyatv/interface.html, pyatv/__init__.py, pyatv/core/__init__.py, pyatv/core/facade.py, pyatv/core/protocol.py, pyatv/core/relayer.py, pyatv/interface.py, pyatv/protocols/__init__.py, pyatv/protocols/airplay/__init__.py, pyatv/protocols/companion/__init__.py, pyatv/protocols/dmap/__init__.py, pyatv/protocols/mrp/__init__.py, pyatv/protocols/raop/__init__.py, tests/core/test_core.py, tests/core/test_facade.py, tests/core/test_protocol.py, tests/core/test_relayer.py, tests/test_interface.py
The idea with this PR is to override the power state (if it is "off") whenever something starts to play and set it to "on" instead. A lot of internal changes have been made to make this happen, which means I'm halfway through with a few other issues (which I will take care of later).
Fixes #1500
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/1519"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> facade: Sync power state with play state

chickn.yaml, docs/api/pyatv/exceptions.html, pyatv/core/facade.py, pyatv/exceptions.py, pyatv/support/shield.py, tests/conftest.py, tests/core/test_facade.py, tests/support/test_shield.py
Use shielding to block calls to all public methods after closing the connection (or disconnecting for any reason).
Relates to #1415
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/1527"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> facade: Block calls to public methods after close

CHANGES.md, pyatv/const.py
Here is yet another release with a bunch of bug fixes and improvements:
* Calling public interface methods after disconnecting now results in `BlockedStateError` being raised
* `power_state` now depends on `device_state`. Because of the unreliable method used to derive `power_state`, a device could be reported as powered off while playing some media, which doesn't make sense. As long as `device_state` is not `idle`, the power state will be reportedas on.
* Button presses in MRP should be more reliable and not skipped or repeated now.
* `netifaces` has been replaced by `ifaddr` due to lack of a maintainer.
* A few fixes have been made for MRP on devices running tvOS <= 14.
* The pause `pause` in RAOP will now stops playback. This is merely because it's not implemented yet and aligns better …
=> Release 0.9.8

pyatv/core/__init__.py, pyatv/protocols/airplay/__init__.py, pyatv/protocols/mrp/__init__.py, pyatv/protocols/mrp/protocol.py, tests/core/test_facade.py
The wrong protocol was used in the ProtocolStateDispatcher passed to
MRP, so play state updates didn't reach the power implementation in
facade. Hopefully this will make the implementation more stable.
Relates to #1500
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/1541"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> mrp: Fix protocol bug in state dispatcher

pyatv/core/__init__.py, pyatv/protocols/companion/__init__.py, pyatv/protocols/mrp/__init__.py, pyatv/protocols/raop/__init__.py, tests/conftest.py, tests/core/test_facade.py, tests/protocols/mrp/test_mrp_interface.py, tests/protocols/raop/test_raop_functional.py
raop: Override volume from other protocols
The volume state in RAOP was (potentially) only derived by the first connection made to the remote device. Mainly becuase no persistent connection is maintained. This resulted in the volume level getting out of sync very easily. Now RAOP will update volume changes according to what other protocols are dispatching.
Relates to #1522
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/1542"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> raop: Override volume from other protocols

pyatv/protocols/airplay/__init__.py, pyatv/protocols/airplay/utils.py, tests/protocols/airplay/test_airplay.py, tests/protocols/airplay/test_utils.py, tests/protocols/raop/test_raop.py
Look at status flags instead of feature flags as they tell what is
required and not only what is supported.
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/1544"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> airplay: Fix pairing requirement bug

docs/api/pyatv.html, pyatv/__init__.py, pyatv/core/__init__.py, pyatv/protocols/__init__.py, pyatv/protocols/airplay/__init__.py, pyatv/protocols/companion/__init__.py, pyatv/protocols/companion/api.py, pyatv/protocols/dmap/__init__.py, pyatv/protocols/mrp/__init__.py, pyatv/protocols/raop/__init__.py
Initial steps to move shared services to a common Core instance. Each
protocol has its own Core instance which is specific to the protocol.
Note that this is only the first step, many improvements can be made
within the protocol to use this new instance.
Relates to #1141
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/1552"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> core: Introduce Core in protocols

pyatv/protocols/raop/audio_source.py, requirements/requirements_test.txt
It seems like urllib is blocked by Cloudflare so better to use a more
capable client, i.e. requests. The code has also been tidied up and
error handling improved.
Relates to #1546
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/1553"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> raop: Use requests instead of urllib in web stream

.github/workflows/release.yml
Building docker images for ARMv7 seems broken, so disable for now.
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/1557"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> gha: Don't build for armv7

docs/api/pyatv.html, pyatv/protocols/raop/__init__.py
Did not call the seekable method properly so metadata would be extracted
from buffered streams, which would fail as that is not supported.
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/1556"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> raop: Fix stream from buffer bug

CHANGES.md, pyatv/const.py
It's a new year and time for a new release with a few bug fixes:
* Play state was reported inconsistently with iOS (MRP) and is now fixed
* Pairing requirement was incorrectly reported as mandatory for Companion
and AirPlay in some cases
* All internal resources are now de-allocated when a connection is closed or
lost, so no need to call for instance push_updater.stop
* Initial support to scan with python-zeroconf. Internal multicast and unicast
methods will be ported to this over time.
This release drops support for python 3.6, mainly due to python-zeroconf not
supporting that version. My intention is to not support EOL versions of python
in the future.
**Changes:**
*Protocol: MRP:*
```
02202ff mrp: Fix play state bug
```
*Protocol: AirPlay:*
```
da51ff4 airplay: Fix pairing requirement …
```
=> Release 0.10.0

base_versions.txt, pyatv/support/chacha20.py, requirements/requirements.txt
I built this for HomeKit but I realized its used here heavily as well
when profiling since I was seeing the ctx get created over and over
even after the HomeKit changes.  It also seems to fix the Home app
stalling out on iOS 16 betas when using them with Home Assistant's
HomeKit integration.
The ChaCha20Poly1305 that comes with cryptography recreates the
ctx every time encrypt is called. Since we call encrypt in
a loop, we can avoid this overhead by using ChaCha20Poly1305Reusable
instead as we are doing everything in the same thread.
Since `pyatv` is sending back and forth encrypted bytes frequently
with the `heartbeater` this reduces the memory churn and cpu
load if you have a few apple tvs or homepods
=> Switch to using ChaCha20Poly1305Reusable for encryption

pyatv/protocols/raop/raop.py
Relates to #1771
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/1775"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> raop: Increase late warning to five frames

chickn.yaml, pyatv/helpers.py, pyatv/protocols/raop/__init__.py, tests/test_helpers.py
If device id is not present in the Zeroconf name, use public key of
device as unique identifier (if present).
Relates to #1747
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/1777"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> raop: Fallback to pk as unique id

CHANGES.md, docs/api/pyatv.html, docs/api/pyatv/helpers.html, pyatv/const.py
This is a minor bug fix release, taking care of some nasty stuff:
* Do not block event loop when streaming audio from a network source
* Support RAOP devices with invalid names
* Add support for `channel_up` and `channel_down` (only Companion so far)
* Increase encryption performance with `ChaCha20Poly1305Reusable`
* Discovery should work better on Windows now
Have a splendid summer!
**Changes:**
```
4c3ef81 raop: Fallback to pk as unique id (#1777)
5805f2c raop: Not do blocking I/O while streaming (#1776)
da184b9 raop: Increase late warning to five frames (#1775)
6195324 raop: Harmonize protocol string in requests
```
*Other:*
```
31de26a Implement channel_up and channel_down (#1769)
d69554e protobuf: Add more fields to DeviceInfoMessage (#1778)
36261f1 mdns: Suppress …
```
=> Release 0.10.1

CHANGES.md, pyatv/const.py
This release just lowers the required version of cryptography
to 36.0.2 or higher.
**Changes:**
*Other:*
```
ecada17 deps: Require cryptography >= 36.0.2 (#1780)
```
```
ecada17 deps: Require cryptography >= 36.0.2 (#1780)
```
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/1781"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Release 0.10.2

base_versions.txt, pyatv/protocols/mrp/protocol.py, pyatv/support/http.py, pyatv/support/rtsp.py, requirements/requirements.txt
I keep forgetting to do this, and I keep using `asyncio.wait_for` in places where
`async_timeout` would be better, but Martin reminded me that we should be
using `async_timeout` where we can in https://github.com/home-assistant/core/pull/75848
so it made me remember here as well.
`async_timeout` is already a dep of aiohttp which uses `async_timeout`
since its much faster than `asyncio.wait_for`
https://pypi.org/project/async-timeout/
=> Switch out asyncio.wait_for with async_timeout in hot paths

CHANGES.md, pyatv/const.py
This is another minor release:
* Adds device info and operating system to atvscript
* Fixes a bug in set_volume on some devices, e.g. HomePod
* Use async_timeout instead of asyncio.wait_for
**Changes:**
*Protocol: MRP:*
```
88547ac mrp: Fix set_volume bug
```
*Script: atvscript:*
```
5edeeb8 atvscript: Add operating_system and version
fdae0b7 atvscript: Add device_info section
7704faa atvscript: Add model and model_str to scan
```
*Other:*
```
d9e1cc5 Switch out asyncio.wait_for with async_timeout
5a20486 conf: Add model_str property
0e03ad5 cq: Remove cruft files
```
```
88547ac mrp: Fix set_volume bug
d9e1cc5 Switch out asyncio.wait_for with async_timeout
ddba0fb build(deps): Bump types-requests from 2.28.1 to 2.28.3 in /requirements
951ea53 build(deps): Bump bitarray …
```
=> Release 0.10.3

docs/documentation/getting_started.md
Hey, in the current getting started page , the current redirect to documentation and development is giving a 404 error as the redirect link was incorrect.
=> Redirecting to correct page

docs/api/pyatv/const.html, docs/api/pyatv/interface.html, pyatv/const.py, pyatv/core/facade.py, pyatv/interface.py, pyatv/protocols/companion/__init__.py, pyatv/protocols/companion/api.py, pyatv/scripts/atvremote.py, tests/fake_device/companion.py, tests/protocols/companion/test_companion_functional.py
This PR adds support for switching the active user account through the companion protocol like the shortcuts app action. Supported operations are reading a list of account names and ids, and changing the account by id.
=> Added support for companion protocol account switching

pyatv/support/http.py
Fixes timeout when streaming audio via airplay.
Relates to #1942
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/1959"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> http: Increase timeout for http requests

pyatv/protocols/mrp/__init__.py, tests/fake_device/mrp.py, tests/protocols/mrp/test_mrp_functional.py
Missing artwork has been reported at #1848 and https://github.com/home-assistant/core/issues/81185https://github.com/home-assistant/core/issues/81185.
My own investigation shows that this is not an issue isolated to HomePods. tvOS seems to only fetch the artwork locally for select media sources - it does for video media from streaming apps, but does not for music media from Apple Music (instead returns links to itunes artwork hosted by Apple).
This PR will fetch the artwork from the `artworkIdentifier` or `artworkURL` fields of the metadata if available.
Home Assistant supports returning artwork urls instead of artwork data, but that would require an API change in pyatv so I wend with this approach.
=> Fix missing artwork

.github/workflows/tests.yml, setup.py
It is no longer supported and most other dependencies no longer support it.
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/1969"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> deps: Deprecate python 3.7

CHANGES.md, pyatv/const.py
@michalmo has been working hard to bring you this release.
It featuers the following:
* Text/keyboard input API (get and alter current text)
* Listener interface for volume updates (+ bug fix for MRP)
* Updates to make atvproxy work with Companion (for devs)
Thanks for your hard work @michalmo, it's really great to get
some help since I don't have much time for pyatv right now. I
know a lot of people are waiting for these features.
**Changes:**
*Other:*
```
34c719c Add support for companion protocol text input (#1905)
39e4d08 Make sure were sending and receiving volume messages for our device, even if playing to other AirPlay devices in a group (#2006)
ccf8a8c Fix companion proxy (#1912)
7c3707b added listener interface to Audio for volume updates
```
```
931b808 …
```
=> Release 0.12.0

chickn.yaml, scripts/chickn.py
GitHub actions always rebuilds miniaudio because of reasons. It however always uses the latest released version, not the pinned version. Since current version (1.58) is broken (does not build), it breaks workflows for pyatv on GitHub actions. This change makes sure we always use the pinned version.
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/2012"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> env: Install correct miniaudio on GHA

.github/workflows/release.yml, Dockerfile
Install dependencies specified in requirements.txt to avoid potentially broken dependencies (like miniaudio currently is).
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/2015"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> gha: Fix building docker images

.github/workflows/log.yaml
Must quote 3.10, otherwise it becomes 3.1.
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/2028"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> gha: Fix python version in logs workflow

docs/documentation/supported_features.md, pyatv/support/rtsp.py
Fixes #1822. Since pyatv 0.10.0 the client cannot stream to a shairport-sync device, see the issue for more details.
I don't really know anything about AirPlay so this change may have an impact on other devices, but it would be good if this can be looked at as it also fixes https://github.com/home-assistant/core/issues/76843.
=> Fix shairport-sync player support

docs/documentation/atvproxy.md, pyatv/support/opack.py, tests/support/test_opack.py
Companion protocol appears to bee sensitive to the byte-size of opack encoded integers. Previously proxy connection could sometimes fail if the size of the response "_x" field did not match the size of the request "_x" field.
This PR preserves  integer sizes when decoding/re-encoding with opack
=> Fix intermittent companion proxy connection issues

docs/_config.yml, docs/api/pyatv/const.html, docs/api/pyatv/interface.html, docs/development/keyboard.md, docs/development/listeners.md, docs/documentation/atvscript.md, pyatv/const.py, pyatv/core/__init__.py, pyatv/core/facade.py, pyatv/interface.py, pyatv/protocols/companion/__init__.py, pyatv/protocols/companion/api.py, pyatv/scripts/atvscript.py, tests/conftest.py, tests/core/test_facade.py, tests/fake_device/companion.py, tests/protocols/companion/test_companion_functional.py, tests/protocols/companion/test_companion_interface.py
This PR adds a listener interface for updating the focus state of the virtual keyboard, and documentation for the Keyboard interface as discussed in comments to #1905.
I've opted to not create a listener for text content, or to pass the current text as part of the focus state update since my testing has found this unreliable. The device only sends text updates for changes made through on screen clicks, not made over the API, and only appears to have started doing so in a patch release that occurred after developing the initial PR. Using text_get gets the actual content always by resetting the text input session before each request.
=> Keyboard focus events and documentation

.github/workflows/release.yml, CHANGES.md, docs/api/pyatv/interface.html, pyatv/const.py
Time for a new release. Here it goes:
* Support for custom metadata when streaming audio
* StreamReader (asyncio) can be used as streaming audio source
* @a1ex4 fixed compatibility with shairport-sync
* @michalmo added listener interface for keyboard focus
* @Shraymonks added a few new tvOs versions and ATV 4K gen3
* @michalmo addded deep linking support to launch_app
A little of this and a little bit of that. It's so much fun
to see new contributors to the project! I love it, keep up
the good work!
**Changes:**
```
e538496 raop: Support custom metadata when streaming (#2011)
ec6a9fd raop: Support asyncio StreamReader when streaming (#2010)
```
*Other:*
```
8b3c15e added listener interface to Keyboard for focus updates
ed7ac4b Fix shairport-sync player support
9ef3ddc …
```
=> Release 0.12.1

.github/workflows/release.yml, CHANGES.md, pyatv/const.py
This release contains some big new stuff, really nice. In summary we have:
* Basic support for audio streaming using AirPlay 2
* Proper power state support in Companion
* Support for activating screensaver
* Improved buffering of audio when streaming
* Added support for changing output devices in tvOS (@michalmo)
* atvproxy now supports MRP-over-AirPlay (@michalmo)
* Bug: Absolute/relative volume management is greatly improved (@michalmo)
* Bug: Position calculation improved in MRP
One of the big new things in this release is support for streaming audio via
AirPlay 2. Streaming via AirPlay 1 has been possible for quite some time now
and that is "good enough" (based on what pyatv supports) with Apple devices,
but not most 3rd party receivers as lots of them only support AirPlay 2. From
now …
=> Release 0.13.0

pyatv/protocols/raop/alac.py, pyatv/protocols/raop/audio_source.py, pyatv/protocols/raop/protocols/airplayv2.py, pyatv/protocols/raop/stream_client.py, pyatv/support/buffer.py, pyatv/support/rtsp.py, tests/fake_device/raop.py, tests/support/test_buffer.py
Audio is now sent as raw PCM samples instead of being encapsulated into ALAC frames. This gives a big performance boost since data is no longer unaligned. Also made some other optimizations, so it should be less stressful on low end systems.
Relates to #2057 
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/2059"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> raop: Send audio as raw PCM

pyatv/const.py, pyatv/convert.py, pyatv/support/device_info.py, tests/test_convert.py
Fixes #2060
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/2061"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> device: Add second generation HomePod

CHANGES.md, docs/api/pyatv/const.html, docs/api/pyatv/convert.html, pyatv/const.py
Small patch release coming up! Second generation HomePod has
been added as device type. A bug when streaming from a buffer
(something inheriting BufferedIOBase) has been fixed. The bug
would render metadata detection unusable and playback to cut
off early.
Previous releases would send raw PCM samples encapsulated in
Apple Lossless Audio Codec (ALAC) frames. This is now changed
to send pure raw audio frames instead (without ALAC). This
has a big benefit in regards to performance as the ALAC
header is not byte-aligned, so it required a lot of bit
shifting and memory copying. This was extremly noticable on
low-end systems like raspberry pi. Hopefully the performance
is a lot better now. Issue #2057 contains more details
regarding this for those interested.
**Changes:**
``` …
```
=> Release 0.13.1

docs/api/pyatv/helpers.html, pyatv/helpers.py, tests/test_helpers.py
Add helper method is_device_supported, returning a boolean indicating if the device is supported by pyatv.
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/2072"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> helpers: Add is_device_supported

docs/api/pyatv/interface.html, docs/development/stream.md, pyatv/interface.py, pyatv/protocols/raop/stream_client.py, pyatv/support/__init__.py, pyatv/support/metadata.py, pyatv/support/rtsp.py, tests/fake_device/raop.py, tests/protocols/raop/test_raop_functional.py, tests/support/test_support.py
Artwork can now be set via cuatom metadata.
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/2076"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> raop: Allow setting artwork

.github/workflows/release.yml, CHANGES.md, pyatv/const.py
Hitting it hard with new releases lately, here's another one:
* Artwork can now be set when streaming
* Metadata can be overridden only when missing
* New helper method: helpers.is_device_supported
* `bitarray` dependency has been dropped (no longer needed)
* Bug: AirPlay in macOS is ignored until I can support it
* Bug: Improved AirPlay 2 detection
So, this release makes it possible to provide artwork as part of metadata when
streaming files. It also adds a new flag, `override_missing_metadata`, that
(when set) will use metadata provided by what is streamed but use custom
metadata when some fields are missing. So if `title` is not in the stream, you
can now provide that but still keep things like `album` and `artist` from
the stream.
A new helper method, `helpers.is_device_support`, has …
=> Release 0.13.2

pyatv/protocols/airplay/pairing.py, pyatv/protocols/raop/__init__.py
Fixes #2092
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/2093"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> raop: Use correct auth type for RAOP pairing

pyatv/protocols/mrp/__init__.py, tests/protocols/mrp/test_mrp.py
Relates to #1567
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/2099"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> mrp: Fix pairing requirement when disabled

README.md, chickn.yaml, docs/api/pyatv/exceptions.html, docs/api/pyatv/interface.html, pyatv/exceptions.py, pyatv/protocols/airplay/__init__.py, pyatv/protocols/airplay/player.py, pyatv/protocols/raop/protocols/__init__.py, pyatv/protocols/raop/protocols/airplayv1.py, pyatv/protocols/raop/protocols/airplayv2.py, pyatv/protocols/raop/stream_client.py, pyatv/protocols/raop/timing.py, pyatv/scripts/atvproxy.py, pyatv/support/http.py, pyatv/support/rtsp.py, tests/protocols/airplay/test_airplay_player.py, tests/support/test_http.py
The play_url method has been broken for a very long time as I believed
Apple wasn't maintaining the underlying functionality anymore. They do,
but an AirPlay session must be established for it to work now. So I
have added that and verified with an Apple TV 3 and 4K running
tvOS 14.5.
Relatest to #2064
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/2079"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> airplay: Fix play_url with newer tvOS versions

CHANGES.md, pyatv/const.py
Time for a somewhat minor fix release:
* The play_url functionality has been restored on tvOS
* Pairing requirement is correctly determined for macOS
* macOS has been added as an operating system
* @bdraco has made some performance improvements when
scanning for devices
**Changes:**
*Protocol: MRP:*
```
dfcc82b mrp: Add some missing protobuf definitions
5ad5103 mrp: Fix pairing requirement when disabled
```
*Protocol: AirPlay:*
```
54ff39e airplay: Handle Access Control Type
c5772b3 airplay: Support stop with play_url
c554ab7 airplay: Fix play_url with newer tvOS versions
```
```
fef1667 raop: Use correct auth type for RAOP pairing
```
*Other:*
```
8022f68 Rework zeroconf for unicast scanning (#2083)
42130e1 conf: Add macOS as operating system
8b572fe http: Abort timeout …
```
=> Release 0.13.3

pyatv/__init__.py, pyatv/core/scan.py, tests/core/test_scan.py
fixes https://github.com/home-assistant/core/issues/95768
I came up with a pretty good way to test this.  I moved my sonos roam to the edge of wifi range to the point were it had significant packet loss and removed the filters in HA. I'm now able to add the roam when the wifi has significant packet loss. This is effectively the same problem as why Passive Observation Of Failures (POOF) is unviable for setups where the responders are on Wi-Fi
By design we only send one unicast packet to do the fallback query to minimize the network and processing impact.  If the network is flakey Home Assistant is going to retry setup again anyways and the next attempt is likely to be successful. 
This is a bit complex because the unicast scanner takes a list of hosts so we have to send to handle that case …
=> Fallback to sending unicast PTR queries when multicast is broken or packets are being dropped

CHANGES.md, docs/api/pyatv.html, pyatv/const.py
@bdraco cleaned up in aisle four and made scanning more
robust in shaky networks, thanks!
**Changes:**
*Other:*
```
17d130a Fallback to sending unicast PTR queries when multicast is broken or packets are being dropped (#2122)
b64bdf9 gha: Remove log workflow (#2120)
```
```
17d130a Fallback to sending unicast PTR queries when multicast is broken or packets are being dropped (#2122)
b64bdf9 gha: Remove log workflow (#2120)
```
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/2127"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Release 0.13.4

.github/dependabot.yml, Dockerfile
I use the pyatv Docker container for building the [pyatv-mqtt-bridge](https://github.com/sebbo2002/pyatv-mqtt-bridge) container. Due to that, I noticed that the Alpine image as well as the Python version used for the pyatv image is comparatively old.
I [updated the Python base image from 3.9.7 to 3.11.4](https://github.com/postlund/pyatv/commit/c3c2dfdbbb6c025acdc42cefced706724c2238c1) and also [enabled Dependabot for the Dockerfile](https://github.com/postlund/pyatv/commit/04d6d985dc847bf2d5db29950e69f99bd6eb1b21), so that the base image is kept up to date. Hope it works, I don't know anything about Python so I didn't even try it.
Thanks 👋🏼
=> Update python dependency and enable Dependabot for Dockerfile

CHANGES.md, docs/api/pyatv.settings.html, pyatv/const.py
Finally time for a new release and this (despite the few number of commits) is a big one: this release introduces the storage API! In reality, the storage API comes with two distinct features:
* Storing and loading of credentials and passwords
* Support for generic settings
The first one is pretty obvious and also the biggest one here. From now on, pyatv will automatically save credentials to a file when pairing and automatically load them again without the need of manually specifying them (the same applies to passwords aswell). This is true for built in scripts like `atvremote` and `atvscript`. You need to add a few lines of code to support it within your applications.
The API is generic in the sense that you can implement your own storage if you like. Perhaps you want to store your …
=> Release 0.14.0

docs/api/pyatv.storage.file_storage.html, docs/development/storage.md, examples/storage.py, pyatv/scripts/__init__.py, pyatv/storage/file_storage.py
This is the default storage used internally by pyatv, but is also open for everyone else to use. There were some issues with paths on Windows, so this solves that as the path is platform agnostic.
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/2169"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> storage: Add FileStorage.default_storage

pyatv/scripts/atvremote.py
Passed storage as incorrect argument to pair. Not sure how mypy did not catch that.
Relates to #2192
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/2195"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> atvremote: Fix storage passing to pair

docs/api/pyatv.settings.html, docs/documentation/atvremote.md, pyatv/protocols/airplay/__init__.py, pyatv/protocols/airplay/pairing.py, pyatv/protocols/airplay/utils.py, pyatv/protocols/raop/__init__.py, pyatv/scripts/atvremote.py, pyatv/settings.py, tests/protocols/airplay/test_utils.py
The setting `protocols.raop.protocol_version` can be set to auto, 1 or 2 to force a specific AirPlay version instead of always falling back to automatic mode.
Relates to #2204
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/2206"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> raop: Add protocol_version setting

CHANGES.md, docs/_includes/atvremote_scan, pyatv/const.py
Minor release coming up today:
* Fix Companion credentials not being saved when pairing
* Actually use storage in the wizard (atvremote)
* Add FileStorage.default_storage() to get the same storage
as used by scripts shipped with pyatv (i.e. you can share
credentials with your applications)
* Add setting to force AirPlay version to use with RAOP
* Add settings for RAOP control and timing ports
**Changes:**
*Protocol: Companion:*
```
e551954 companion: Fix credentials not saved
```
```
c17f304 raop: Add protocol_version setting
391be8b raop: Add settings for timing and control ports
```
*Script: atvremote:*
```
fa2f7b1 atvremote: Fix storage passing to pair
```
*Other:*
```
fd7135b tests: Add test for atvremote wizard
e8a812d tests: Migrate scripts tests to pytest
6704359 …
```
=> Release 0.14.1

pyatv/interface.py
Hi! I'm working on enabling [strict typing check](https://github.com/home-assistant/core/blob/dev/.strict-typing) for home assistant `apple_tv` integration. Currently, pyatv is not declared as PEP-561 compliant which causes mypy to [ignore all imports from pyatv](https://github.com/home-assistant/core/actions/runs/6454672708/job/17521010925?pr=101688).
Since most of pyatv are already typed, we can safely add a `py.typed` to mark this library as PEP-561 compliant.
See: https://blog.whtsky.me/tech/2021/dont-forget-py.typed-for-your-typed-python-package/
=> add py.typed to mark pyatv as PEP-561 compliant

pyatv/protocols/companion/protocol.py, pyatv/protocols/mrp/protocol.py, pyatv/support/__init__.py
Use error_handler when connecting to pass-through a few exceptions, to enaure they are not hidden behind an AuthenticationError. This helps a lot in Home Assistant currently.
Relates to #2242
=> api: Use error_handler when connecting

CHANGES.md, pyatv/const.py
Due to Home Assistant being stuck at pydantic v1 at the moment,
I have now changed to use pydantic v1 with the compatibility
version bundled in v2. This bascially means that pydantic v1 is
used internally, even when v2 is installed. This is temporary
until Home Assistant can bump up to pydantic v2. I have also
removed dependency on pydantic-extra-types (only MacAddress was
used) as it has no v1 compatible version. Same goes for
pydantic-settings, which provides no functionality currently.
**Changes:**
*Other:*
```
86a4a91 storage: Use pydantic v1 compatibility
1a8c05a storage: Remove usage of pydantic-settings
d95ab81 storage: Remove need for pydantic-extra-types
b671e21 cq: Another attempt to fix update_type
e50fb7b cq: Specify depdency_type to auto-merge
bde83fa cq: Update auto-merge …
```
=> Release 0.14.3

pyatv/scripts/atvscript.py, pyatv/support/knock.py
Hello everybody,
yesterday I reported the bug #2268.
Today, I have taken a look at the problem. It was a fairly easy fix. The problem was that [asyncio.wait](https://docs.python.org/3/library/asyncio-task.html#asyncio.wait) forbidds to pass coroutine objects directly since Python 3.11.
To fix this issue, the coroutines can just be wrapped in a task by utilizing [asyncio.create_task](https://docs.python.org/3/library/asyncio-task.html#asyncio.create_task).
If there are any questions, feel free to ask :).
=> Wrap coroutines passed to asyncio.wait with create_tasks because asyncio.wait does not support passing coroutines since python 3.11

CHANGES.md, pyatv/const.py
This release contains a fix when running with python 3.11
or later, mainly when calling atvscript. Thanks @maxileith!
**Changes:**
*Other:*
```
cc0e4a2 Wrap coroutines passed to asyncio.wait with create_tasks asyncio.wait does not support passing coroutines since python 3.11
d8c6b4d cq: New attempt with token
e611672 cq: New token for auto-merge
b47ddbf cq: Update auto-merge token
e7f880a cq: Try to fix auto-merge
```
```
cc0e4a2 Wrap coroutines passed to asyncio.wait with create_tasks asyncio.wait does not support passing coroutines since python 3.11
d8c6b4d cq: New attempt with token
e611672 cq: New token for auto-merge
b47ddbf cq: Update auto-merge token
e7f880a cq: Try to fix auto-merge
```
=> Release 0.14.4

docs/documentation/atvscript.md, pyatv/scripts/atvscript.py, tests/scripts/test_atvscript.py
Hi @postlund ,
for the use-case I am currently working on, I use Airplay MAC-Adresses as an identifier https://github.com/maxileith/homebridge-appletv-enhanced/issues/20. Therefore, I always need to get the MAC-Address as an identifier from `atvscript`. However, currently the returned identifier from `atvscript scan` is not always the MAC-Address. Therefore, I would suggest to add an attribute `all_identifieres` to the output json. By not touching `identifier` of the output json, backward compatability is given.
I'd love to hear your thoughts on that.
=> Output all identifiers and mac address when scanning with atvscript

docs/index.md
Hi @postlund ,
I am currently developing a homebridge plugin that is already in a very solid state. I would suggest to replace the currently featured but not maintained homebridge plugin (seems like it when looking at the open issues) from @cristian5th with this maintained one. Also my plugin is more native, since it does not provide a configuration for another homebridge plugin but is a homebridge plugin by itself.
@cristian5th you are welcome to join the discussion
=> Changing the featured Homebridge plugin to a more recent and maintained one.

pyatv/scripts/atvscript.py
Hi,
I have noticed a bug which causes the `atvscript push_updates` command to never report the App that is currently playing. I believe this bug was caused in https://github.com/postlund/pyatv/pull/1962 which solves https://github.com/postlund/pyatv/issues/1930.
The solution in https://github.com/postlund/pyatv/pull/1962 is supposed to be checking wether or not the `App` feature is available and only then return it. https://github.com/postlund/pyatv/blob/b35b7ba9bcc93c11754c61ebd99f0cb88d0ce3f2/pyatv/scripts/atvscript.py#L48 However, I think that this is supposed to look like one if these two options:
```python
if not self.atv.features.get_feature(FeatureName.App).state == FeatureState.Unavailable
```
```python
if not self.atv.features.in_state(FeatureState.Unavailable, FeatureName.App) …
```
=> Fix a bug that causes atvscript push_updates to never report the current app

CHANGES.md, pyatv/const.py
Merry christmas everyone, here comes a small present! In this
release @maxileith made some improvements to atvscript. App should be
reported correctly now. All identifiers as well as MAC address is
ouputted when scanning. Other than that it's merely house-keeping.
Been rather slow work on pyatv for a while, let's see what the new
year might bring!
**Changes:**
*Other:*
```
0da3258 scan: Fix python-zeroconf incompatibility
454afc0 Fix a bug that causes atvscript push_updates to never report the app
8d883fb update the list of contributors
8be2b64 Changing the featured Homebridge plugin to a more recent and maintained one.
2da50e9 add mac address to device info
0937a7b Output all identifiers when scanning with atvscript
```
```
ce61b49 build(deps): Bump black from 23.9.1 to …
```
=> Release 0.14.5

pyatv/support/chacha20.py
similar change to
https://github.com/esphome/aioesphomeapi/blob/c9227edf7fcee0f175c9f31c024ba71b0a0fac26/aioesphomeapi/_frame_helper/noise.py#L31
https://github.com/ikalchev/HAP-python/blob/dev/pyhap/hap_crypto.py#L17
`pack` is a bit faster than `to_bytes`
=> Simplify ChaCha20 Poly1305 implementation

base_versions.txt
Cryptography 43.0.0 and needed by chacha20poly1305-reusable, so bumping to that. Should fix #2451.
Relates to #2451
=> deps: Bump some lowest deps versions

CHANGES.md, docs/api/pyatv.const.html, docs/api/pyatv.interface.html, pyatv/const.py
It has been a long time since the last release (christmas!), so a it's really
due for a new one. I have mostly been busy with other (personal) stuff, so I
have not done much more than maintenance. There are a few changes from the
community though.
Some hightlights:
* Uplift of various dependencies, e.g, fix breaking change in cryptography
* It is possible to skip forward/backwards (Companion) with custom intervals,
thanks @thiccaxe!
* @bdraco fixed a bug related to changes in chacha20poly1305-reuseable
* Python 3.12 is now (finally) offically supported
This is a minor update indeed. I hope to see some updates in the near future,
especially related to tvOS 18 compatibility as well as new features. I am very
grateful for any help from the community. So if you want to help out
implementing …
=> Release 0.15.0

pyatv/protocols/raop/protocols/airplayv2.py
Audio streaming broke in the previous version due to nonce length changes. Apparently the encryption output counter was wrongly implemented as well (counter was always zero). Apple devices seems to be fine with that, but maybe some other devices doesn't like it? That is fixed now.
Relates to #2479
=> raop: Fix broken audio streaming

pyatv/support/opack.py, tests/support/test_opack.py
https://github.com/postlund/pyatv/issues/2403#issuecomment-2267340404
=> opack: fix byte encoding length

CHANGES.md, pyatv/const.py
Okie-dokie, let's do this. Due to Python 3.13 removing some deprecated
modules, you might have encountered an import error related to
`imghdr`. This module is not used directly by pyatv, but rather
indirectly via the `mediafile` library. As `mediafile` is not
maintained much these days, I decided to replace it with `tinytag`
instead. I have also added python 3.13 as an offically supported
version.
Another somewhat related change is that Python 3.8 is no longer
supported. It is end-of-life and some of my dependencies are
dropping support for it, so it's hard to maintain. Good bye,
old friend!
There are some new stuff as well:
* It is possible specify filename with `artwork_save` in `atvremote` (@AVITPL)
* Input actions are now fully supported in Companion (@dmrgn1991)
* iTunes Store …
=> Release 0.16.0

docs/documentation/protocols.md
There was a typo ('vevsion') so I fixed that, then scanned to see if there was anything else worth changing, and came across an acronym that wasn't defined at its first use, so I tweaked that too.
=> Fix typo, expand acronym at first use

base_versions.txt
Earlier versions has a vulnerability so we should not support that.
=> deps: Set cryptography 44.0.1 as base version

docs/api/pyatv.settings.html, pyatv/protocols/airplay/__init__.py, pyatv/scripts/atvremote.py, pyatv/settings.py
It is now possible to force or disable set up of MRP over AirPlay tunnel over Airplay (or the default "auto" mode). If set up of remote control fails, that will now render an exception (just like with other protocols on an error) instead of just a log message.
Relates to #2629
=> airplay: Add setting for MRP tunnel

CHANGES.md, docs/api/pyatv.const.html, docs/api/pyatv.interface.html, docs/api/pyatv.settings.html, docs/api/pyatv.storage.html, pyatv/const.py
Hey-ho, minor release (finally) that should fix:
* Connection issues with tvOS 18.4+
* Warnings related to protobuf
**Changes:**
*Protocol: AirPlay:*
```
e27164ba airplay: Add setting for MRP tunnel
```
*Protocol: Companion:*
```
607c5e0c companion: Use static id for _i in _systemInfo
```
*Other:*
```
5b1ec5d7 deps: Bump protbuf generated messages
f75e718b deps: Bump protobuf to 30.2
d711126e deps: Set cryptography 44.0.1 as base version
9c221d18 cq: Fix issues with new black
2e20e41b cq: Fix some spelling issues
93707a9d favor companion protocol for power state
cc615074 Fix typo, expand acronym at first use
```
```
6f1a6bd0 build(deps): Bump pytest from 8.3.5 to 8.4.1 in /requirements
f532a9e3 build(deps): Bump cryptography from 45.0.4 to 45.0.5 in /requirements
4d93611a …
```
=> Release 0.16.1
