postlund/pyatv

.gitignore
pyatv/__main__.py

The `artwork` command now saves the artwork to `artwork.png` if the artwork is available.
Closes #4

Artwork fix

---

docs/connecting.rst
docs/finding_devices.rst
examples/autodiscover.py
pyatv/__init__.py
pyatv/__main__.py
pyatv/helpers.py
tests/test_functional.py
tests/zeroconf_stub.py

Also introduces a stub for zeroconf.

Add test for device scanning

---

docs/atvremote.rst
docs/connecting.rst
docs/finding_devices.rst
docs/protocol.rst
pyatv/__init__.py
pyatv/__main__.py
pyatv/daap.py
pyatv/internal/apple_tv.py
tests/fake_apple_tv.py
tests/test_functional.py

This is a preparatory PR for supporting pairing.

Add support for pairing guid

---

pyatv/daap.py
tests/fake_apple_tv.py
tests/test_functional.py

Add automatic re-login if logged out from device

---

.gitignore
requirements_all.txt
setup.py
tox.ini

Should fix some errors when setting things up.

Requirement fixes

---

pyatv/__init__.py
pyatv/airplay.py
pyatv/interface.py
pyatv/internal/apple_tv.py
tests/fake_apple_tv.py
tests/test_airplay.py
tests/test_functional.py

This shall be the final version for now. I will have to make this better later and add more tests, but at least I have a base now.

Play media by specifying a URL

---

pyatv/__main__.py

Just some small fixes i've found...

A small fix undeserving of a pull request

---

CHANGES.rst
CONTRIBUTORS.txt
MANIFEST.in
README.rst
docs/faq.rst

I will probably add more stuff here later.

Various fixes for the upcoming release

---

pyatv/__init__.py
pyatv/airplay.py
pyatv/interface.py
pyatv/internal/apple_tv.py
tests/fake_apple_tv.py
tests/test_airplay.py
tests/test_functional.py

For some reason my other PR says that is is merged, but it isn't. I'll try it again.

Play media based on a URL (re-attempt)

---

docs/testing.rst
pyatv/internal/apple_tv.py
setup.py
tests/test_functional.py

Also fix some errors in the tests so that sessions aren't leaking
anymore. This fixes #1.

Upgrade aiohttp to 1.3.0

---

README.rst
docs/atvremote.rst
docs/index.rst
pyatv/interface.py
pyatv/internal/apple_tv.py
tests/test_functional.py

Rename topmenu to top_menu

---

README.rst
docs/atvremote.rst
docs/metadata.rst
pyatv/daap.py
pyatv/interface.py
pyatv/internal/apple_tv.py
tests/test_functional.py

This function will return URL to current artwork. Note that it is always the same for a session, it is up to the user to determine when "new" artwork is available.

Add function artwork_url

---

.checkignore
pyatv/dmap.py
pyatv/exceptions.py
tests/test_functional.py
tests/zeroconf_stub.py

Should hopefully be fixed now. Feedback is a bit mismatching at the moment...

Fix quantifiedcode issues

---

README.rst
docs/atvremote.rst
docs/index.rst
docs/metadata.rst
docs/protocol.rst
pyatv/__init__.py
pyatv/__main__.py
pyatv/daap.py
pyatv/exceptions.py
pyatv/interface.py
pyatv/internal/apple_tv.py
tests/fake_apple_tv.py
tests/test_functional.py

Here is the much awaited support for push updates, yey!

Support for Asynchronous ("push") updates

---

docs/atvremote.rst
docs/pairing.rst
docs/protocol.rst
examples/pairing.py
pyatv/__main__.py
pyatv/pairing.py
tests/fake_apple_tv.py
tests/test_functional.py
tests/test_pairing.py
tests/utils.py

Mainly clean up and separate tests for pairing.

General improvements to pairing

---

pyatv/__main__.py

Now 0 is returned if command succeeded, otherwise something else is
returned. No other meaning of return value is defined.

Fix return code in atvremote

---

pyatv/convert.py
tests/test_convert.py

Add missing media kinds

---

README.rst
docs/atvremote.rst
pyatv/__init__.py
pyatv/__main__.py
tests/test_functional.py
tests/test_scan.py
tests/zeroconf_stub.py

Scan for devices with Home Sharing disabled

---

pyatv/__main__.py

Handle -v and --debug correctly

---

setup.py

Bump aiohttp to 1.3.5

---

.travis.yml
pyatv/internal/apple_tv.py
setup.py
tox.ini

I don't have python 3.6 on my machine, so I'm just gonna let travis try this for me...

Verify pyatv with python 3.6 in tox

---

CHANGES.rst
CONTRIBUTORS.txt
README.rst
docs/faq.rst
docs/index.rst
docs/troubleshooting.rst
examples/__init__.py
examples/auto_connect.py
examples/autodiscover.py
examples/manual_connect.py
examples/pairing.py
pyatv/__init__.py
pyatv/dmap.py
pyatv/helpers.py
pyatv/interface.py
pyatv/internal/apple_tv.py
requirements_test.txt
tests/fake_apple_tv.py
tests/log_output_handler.py
tests/test_dmap.py
tox.ini

Bump various dependencies and update documentation.

Preparations for release 0.3.0

---

examples/autodiscover.py
examples/manual_connect.py
pyatv/__init__.py
pyatv/__main__.py
pyatv/const.py
pyatv/convert.py
pyatv/dmap/apple_tv.py
pyatv/exceptions.py
tests/dmap/test_functional.py
tests/test_convert.py
tests/test_helpers.py
tests/test_scan.py
tests/zeroconf_stub.py

This PR will make the config used when connecting to a device or scanning for devices more flexible. **It is a breaking change!**
Still not finished, a few more cases to handle and additional tests. New API is not final yet, it will probably change a bit before merge.

WIP: Initial changes to more flexible config

---

pyatv/const.py
pyatv/convert.py
tests/test_convert.py

Add support for idle play state

---

pyatv/interface.py
pyatv/internal/apple_tv.py
pyatv/tag_definitions.py
tests/fake_apple_tv.py
tests/test_functional.py
tests/test_interface.py

Add support for genre

---

pyatv/airplay/player.py
pyatv/const.py
pyatv/internal/apple_tv.py
tests/fake_apple_tv.py
tests/test_airplay.py

Same as #105 but with minor fixes and tests.

Airplay session fixes

---

pyatv/__init__.py
pyatv/airplay/player.py
tests/airplay/test_airplay.py
tests/fake_daap_atv.py

Play state logic

---

README.rst

A small change to make the README example accurate.

Fix command example

---

.travis.yml
README.rst
docs/atvremote.rst
pyatv/__init__.py
pyatv/__main__.py
pyatv/airplay/player.py
pyatv/convert.py
pyatv/dmap/daap.py
pyatv/dmap/pairing.py
pyatv/dmap/parser.py
pyatv/dmap/tags.py
pyatv/exceptions.py
pyatv/interface.py
pyatv/mrp/__init__.py
pyatv/mrp/protocol.py
pyatv/net.py
requirements_test.txt
setup.py
setup_dev_env.sh
tests/airplay/fake_airplay_device.py
tests/airplay/test_airplay.py
tests/dmap/fake_dmap_atv.py
tests/dmap/test_pairing.py

This is a messy commit that picks some of the changes recently made to v0.3.x and applies them to the master branch. Since they code-wise have diverged quite a lot, some fixes had to be made.
The approach from now on until 0.4.0 is released is to just push things in. So I will start with rebasing and fixing all PRs that are not in after this one...

Cherry-pick changes from 0.3-branch to master

---

tests/airplay/fake_airplay_device.py
tests/airplay/test_airplay.py
tests/airplay/test_airplay_auth.py
tests/dmap/fake_dmap_atv.py
tests/dmap/test_dmap_functional.py
tests/mrp/fake_mrp_atv.py
tests/mrp/test_mrp_functional.py

This is just some dummy code to get going with MRP tests. Currently no tests work but all common tests run.

Add initial test code for MRP

---

pyatv/const.py
pyatv/convert.py
tests/test_convert.py

Add support for stopped playstate (state = 2)
Fix for issue #172

Add support for stop play state

---

pyatv/__init__.py
tests/test_scan.py

Ignore services that are not usable.

Fix "abort on found" logic

---

pyatv/__init__.py
pyatv/dmap/__init__.py
pyatv/exceptions.py
pyatv/interface.py
pyatv/mrp/__init__.py
setup.py
tests/common_functional_tests.py
tests/dmap/test_dmap_functional.py
tests/getmac_stub.py
tests/mrp/test_mrp_functional.py
tests/test_interface.py
tests/zeroconf_stub.py

Uses third party library getmac to get it done.

Generate device id based on MAC

---

CHANGES.rst
pyatv/const.py

Second pre-releaee of 0.4.0

---

README.rst
pyatv/dmap/__init__.py
pyatv/dmap/daap.py
pyatv/interface.py
pyatv/mrp/__init__.py
tests/common_functional_tests.py
tests/test_interface.py

Deprecate artwork_url

---

examples/pairing.py
pyatv/__init__.py
pyatv/__main__.py
pyatv/dmap/pairing.py
setup.py
tests/zeroconf_stub.py

First stab at migrating to aiozeroconf. Let's see if it works better.

Migrate from zeroconf to aiozeroconf

---

README.rst
examples/autodiscover.py
examples/manual_connect.py
examples/pairing.py
pyatv/__init__.py
pyatv/__main__.py
pyatv/conf.py
pyatv/dmap/__init__.py
pyatv/exceptions.py
pyatv/helpers.py
pyatv/mrp/__init__.py
pyatv/mrp/protocol.py
scripts/proxy.py
tests/common_functional_tests.py
tests/dmap/test_dmap_functional.py
tests/mrp/test_mrp_functional.py
tests/test_conf.py
tests/test_helpers.py
tests/test_scan.py
tests/zeroconf_stub.py

This commit cleans up the conf module quite a bit. The concept of "usable" has been removed. Also connect_to_apple_tv and scan_for_apple_tvs have been renamed to connect and scan respectively.

Cleanup and renaming

---

scripts/proxy.py

API changed a bit so the proxy broke.

Fix MRP proxy after clean-up

---

scripts/proxy.py

Use aiozeroconf in MRP proxy

---

.travis.yml
scripts/setup_dev_env.sh
setup.py
tox.ini

Add python 3.8 as supported version

---

pyatv/__main__.py

I made a boo boo... Those smoke tests of atvremote would be kinda handy.

Bug fix for previous AirPlay change

---

pyatv/__init__.py
pyatv/__main__.py
pyatv/dmap/__init__.py
pyatv/interface.py
pyatv/mrp/__init__.py
tests/dmap/test_dmap_functional.py

Connect to device when connecting

---

.gitignore
docs/.gitignore
docs/404.html
docs/Gemfile
docs/_config.yml
docs/index.md
scripts/build_docs.sh
scripts/setup_dev_env.sh

This commit includes a place holder page and script to build and preview documentation locally (requires docker).

Intial migration to GitHub pages

---

docs/_layouts/defaults.html

Not sure why theme isn't applying, trying this...

Add defaults layout

---

pyatv/airplay/pairing.py
pyatv/conf.py
pyatv/dmap/pairing.py
pyatv/exceptions.py
pyatv/interface.py
pyatv/mrp/__init__.py
pyatv/mrp/auth.py
pyatv/mrp/pairing.py
pyatv/mrp/player_state.py
tests/test_conf.py

Fixed a couple of things required for the Home Assistant integration, more will likely come but these were kinda necessary.

Regressions for fourth pre-release of 0.4.0

---

docs/documentation/atvremote.md
docs/getting_started.md
docs/support/faq.md
pyatv/__main__.py
pyatv/mrp/pairing.py
setup.py

This fixes #271.
Some additional updates to documentation is included as well.

Specify device with -n in atvremote

---

pyatv/mrp/messages.py
pyatv/mrp/protocol.py

Makes changes mentioned in #204. Not sure if this is enough to fix issue, but it's at least necessary.

Make corrections to MRP flow

---

docs/documentation/atvremote.md
pyatv/dmap/__init__.py
pyatv/interface.py
pyatv/mrp/__init__.py

Add MRP functionality and update documentation with changes

Add MRP functionality

---

examples/manual_connect.py
examples/pairing.py
pyatv/__main__.py
pyatv/airplay/__init__.py
pyatv/airplay/player.py
pyatv/dmap/__init__.py
pyatv/dmap/parser.py
pyatv/interface.py
pyatv/mrp/__init__.py
pyatv/mrp/auth.py
pyatv/mrp/connection.py
pyatv/mrp/messages.py
pyatv/mrp/protocol.py
scripts/proxy.py
tests/airplay/test_airplay.py

General clean-up of various parts

---

scripts/release.py

This script helps out when making a release by updating version numer,
building wheels, creating commits, etc. to ensure that everything is
correct. It doesn't make the release and some functionality I want is
still missing, but I will add that as time goes.

Add initial script to make releases

---

pyatv/airplay/pairing.py

Support leading zeros for PINs in AirPlay

---

pyatv/__main__.py
tests/test_atvremote.py
tests/zeroconf_stub.py

Only scanning and AirPlay pairing is currently tested. This will be
the start. Once more MRP tests are finished so the fake MRP device
(which this tests rely on) are usable, I will add metadata tests.

Add initial smoke tests for atvremote

---

docs/documentation/atvremote.md

Add documentation for manual mode in atvremote

---

pyatv/mrp/__init__.py
tests/airplay/test_airplay.py
tests/common_functional_tests.py
tests/dmap/test_dmap_functional.py
tests/mrp/fake_mrp_atv.py
tests/mrp/test_mrp_functional.py
tests/test_atvremote.py
tests/utils.py
tox.ini

This is an incremental update to tests for MRP, but it contains a lot of
ground work needed for further tests. A tricky part when testing async
code is synchronization when checking the result. This commit adds some
helpers for dealing with that.

Add some additional tests for MRP

---

pyatv/mrp/__init__.py
pyatv/mrp/protobuf/Origin.proto
pyatv/mrp/protobuf/Origin_pb2.py
pyatv/mrp/protobuf/Origin_pb2.pyi
tests/common_functional_tests.py
tests/dmap/test_dmap_functional.py
tests/mrp/fake_mrp_atv.py
tests/utils.py

This only tests paused video. To support playing video, faking time must be done in a clever way. Will deal with that later.

Add first "playing" functional test to MRP

---

pyatv/__main__.py
tests/test_atvremote.py

Additional atvremote tests

---

pyatv/mrp/__init__.py
pyatv/mrp/player_state.py

Fix position in MRP when elapsed time is missing

---

docs/development/scan_pair_and_connect.md
examples/pairing.py
pyatv/__init__.py
pyatv/__main__.py
pyatv/airplay/__init__.py
pyatv/airplay/pairing.py
pyatv/conf.py
pyatv/const.py
pyatv/convert.py
pyatv/dmap/__init__.py
pyatv/dmap/pairing.py
pyatv/mrp/__init__.py
pyatv/mrp/pairing.py
tests/airplay/test_airplay_pair.py
tests/common_functional_tests.py
tests/dmap/fake_dmap_atv.py
tests/dmap/test_dmap_functional.py
tests/dmap/test_dmap_pair.py
tests/test_conf.py
tests/test_convert.py
tests/test_interface.py
tests/test_scan.py

Change from constants to enums in const.py

---

pyatv/__init__.py

Preparations for supporting unicast mDNS lookups.

Refactor scanning code

---

pyatv/mrp/__init__.py

Handle NaN durations in MRP

---

pyatv/mrp/__init__.py

Avoid closing external aiohttp session in MRP

---

pyatv/dmap/pairing.py
tests/dmap/test_pairing.py

Release resources when closing in DMAP pairing

---

pyatv/__init__.py
pyatv/mrp/__init__.py
pyatv/mrp/messages.py
tests/common_functional_tests.py
tests/dmap/test_dmap_functional.py
tests/mrp/fake_mrp_atv.py
tests/utils.py

From this commit all functional tests have been ported to run on both DMAP and MRP, which is pretty great. There are some things missing in MRP yet, so will focus on that.

Migrate last common functional tests

---

requirements_test.txt
setup.py
tox.ini

Run tests in parallel with "auto" amount of workers.

Use pytest-xdist in tox

---

.github/workflows/tests.yml
pyatv/__init__.py
pyatv/mrp/__init__.py
pyatv/mrp/player_state.py
pylintrc

Fix tests on Windows

---

.coveragerc
pyatv/mrp/messages.py
pyatv/mrp/protocol.py
tests/mrp/fake_mrp_atv.py
tests/mrp/test_mrp_functional.py
tests/utils.py

Removed some code that is not currently used. Added a test to cover
CONTENT_ITEM_UPDATE_MESSAGE.
Fixes #241.

Minor clean ups and additional coverage

---

docs/documentation/atvremote.md
docs/support/troubleshooting.md
pyatv/mrp/connection.py
pyatv/support.py
setup.py
tests/test_support.py

Limit log printouts for binary data att protobuf

---

pyatv/dmap/tag_definitions.py
pyatv/dmap/tags.py
tests/dmap/test_parser.py

Add some missing DMAP tags

---

pyatv/convert.py
tests/test_convert.py

Supress unknown DMAP media kind

---

pyatv/dmap/tag_definitions.py

Ignore some unknown DMAP tags

---

pyatv/mrp/player_state.py
tests/common_functional_tests.py
tests/dmap/fake_dmap_atv.py
tests/mrp/fake_mrp_atv.py
tests/mrp/test_mrp_functional.py

Should fix minor state bug and also implement "seeking".

mrp: Fix device state handling

---

pyatv/mrp/__init__.py
pyatv/mrp/player_state.py
tests/mrp/fake_mrp_atv.py
tests/utils.py

mrp: Fix calcuation of position

---

docs/_config.yml
docs/index.md
docs/support/migration.md

docs: Add basic migration instructions

---

CHANGES.md
docs/_config.yml
pyatv/const.py
scripts/release.py

Release 0.4.0

---

docs/_config.yml
docs/development/device_info.md
docs/documentation/atvremote.md
docs/documentation/concepts.md
docs/getting_started.md
docs/index.md
pyatv/__init__.py
pyatv/__main__.py
pyatv/conf.py
pyatv/const.py
pyatv/device_info.py
pyatv/dmap/__init__.py
pyatv/interface.py
pyatv/mrp/__init__.py
tests/common_functional_tests.py
tests/dmap/test_dmap_functional.py
tests/mrp/test_mrp_functional.py
tests/test_atvremote.py
tests/test_conf.py
tests/test_device_info.py
tests/test_interface.py
tests/test_scan.py

This PR introduces an interface to retrieve various kinds device information, e.g. running OS, hardware model, etc. I think I'm ready, but I'm gonna have another look to see if I missed anything. If anyone wants to try it out, please give it a spin!
Fixes #220.

Add device information interface

---

docs/documentation/concepts.md
pyatv/__init__.py
pyatv/conf.py
tests/test_conf.py
tests/test_scan.py

scan: Do not include pure AirPlay devices

---

pyatv/airplay/__init__.py
pyatv/dmap/daap.py
pyatv/mrp/srp.py
tests/airplay/fake_airplay_device.py
tests/common_functional_tests.py
tests/dmap/test_dmap_functional.py

cq: Handle invalid credentials

---

pyatv/__init__.py
pyatv/__main__.py
pyatv/conf.py
pyatv/convert.py
pyatv/helpers.py
pyatv/interface.py

This commit add typing information to the public interface. I will
continue to expand this inside pyatv over time, but only focus on the
interface for now.
Fixes #249.

cq: Add typing hints to public interface

---

docs/_layouts/template.html

Made some mistakes earlier regarding how relative links are create, this should fix that.

docs: Fix relative links

---

pyatv/mrp/__init__.py
pyatv/mrp/player_state.py
tests/mrp/fake_mrp_atv.py
tests/mrp/test_mrp_functional.py

mrp: Support volume control features

---

pyatv/mrp/messages.py
scripts/fake_device.py
tests/mrp/fake_mrp_atv.py

Just first step in state break out. Power state is stored and update in the state.
Relates to #331.

tests: Break out state in MRP fake device

---

docs/api/pyatv/interface.html
docs/documentation/atvscript.md
pyatv/scripts/atvscript.py
tests/scripts/test_atvscript.py

A few new improvements to atvscript:
* Respect -s when scanning
* Include services (protocol and port) when scanning
* Print power state changes

scripts: Add features to atvscript

---

pyatv/airplay/pairing.py
pyatv/mrp/pairing.py
tests/dmap/test_dmap_pair.py
tests/mrp/test_mrp_auth.py

This should make pairing more consistent across all protocols.
Fixes #464.

bug: Make pairing interface consistent

---

docs/api/pyatv.html
pyatv/__init__.py
tests/zeroconf_stub.py

Tasks were kept idling in the background for now reason. This fixes that.

scan: Clean up pending service browsers

---

pyatv/scripts/atvscript.py

atvscript: Treat empty strings as None

---

docs/api/pyatv/interface.html
docs/documentation/atvscript.md
pyatv/scripts/atvscript.py

Print when connection is closed or lost. Also fix a resource leak due
to not closing the atv instance.

atvscript: Add device listener

---

docs/documentation/atvscript.md
pyatv/scripts/atvscript.py
tests/scripts/script_env.py
tests/scripts/test_atvscript.py

atvscript: Add timestamp to output

---

pyatv/mrp/__init__.py
pyatv/mrp/player_state.py
tests/common_functional_tests.py

mrp: Make Playing objects immutable

---

docs/api/pyatv/helpers.html
docs/api/pyatv/interface.html
docs/getting_started.md
docs/support/migration.md
examples/manual_connect.py
examples/scan_and_connect.py
pyatv/dmap/__init__.py
pyatv/helpers.py
pyatv/interface.py
pyatv/mrp/__init__.py
pyatv/scripts/atvremote.py
pyatv/scripts/atvscript.py
tests/common_functional_tests.py
tests/dmap/test_dmap_functional.py
tests/mrp/test_mrp_auth.py
tests/mrp/test_mrp_functional.py
tests/test_helpers.py

if: Change close to not be a coroutine

---

pyatv/scripts/atvscript.py

This adds a few additional hacks to make atvscript more robust to
exceptions and unforseen errors. Hopefully it should reports errors and
exit as it should now.

atvscript: Make more robust to errors

---

pyatv/scripts/atvscript.py

Enabling --debug will append debug logs to atvscript.log.

atvscript: Add debug flag

---

docs/development/control.md
docs/index.md
pyatv/dmap/__init__.py
pyatv/dmap/daap.py
pyatv/mrp/__init__.py
tests/common_functional_tests.py
tests/dmap/test_dmap_functional.py
tests/fake_device/dmap.py
tests/fake_device/mrp.py
tests/mrp/test_mrp_functional.py

dmap: Add support for volume_up and volume_down

---

pyatv/airplay/pairing.py
pyatv/airplay/srp.py
pyatv/dmap/pairing.py
pyatv/mrp/connection.py
pyatv/mrp/pairing.py
pyatv/support/__init__.py
pyatv/support/net.py
tests/support/test_support.py

Added a few new debug logs that I feel is good to have, but also changed
some existing to be more consistent among the protocols.

cq: Various debug log improvements

---

pyatv/support/net.py

net: Change timeout to 25 seconds

---

docs/api/pyatv.html
pyatv/__init__.py
pyatv/scripts/atvremote.py
pyatv/support/knock.py
tests/conftest.py
tests/fake_knock.py
tests/scripts/script_env.py
tests/support/test_knock.py
tests/test_scan.py

See #580 and #595 for more details.
Relates to #595.

udns: Port knock to wake sleeping devices

---

docs/api/pyatv.html
pyatv/__init__.py
pyatv/support/knock.py
tests/conftest.py
tests/fake_knock.py
tests/support/test_knock.py
tests/test_scan.py

knock: Support for continuously knocking ports

---

docs/api/pyatv/interface.html
pyatv/airplay/__init__.py
pyatv/airplay/server.py
pyatv/dmap/__init__.py
pyatv/interface.py
pyatv/mrp/__init__.py

cq: Clean up resources when closing a device

---

docs/development/scan_pair_and_connect.md

docs: Rename variable in credentials example

---

pyatv/mrp/__init__.py
pyatv/mrp/messages.py
pyatv/mrp/protobuf/SendCommandResultMessage.proto
pyatv/mrp/protobuf/SendCommandResultMessage_pb2.py
pyatv/mrp/protobuf/SendCommandResultMessage_pb2.pyi
pyatv/mrp/protobuf/__init__.py
tests/fake_device/mrp.py

mrp: Fixes to support older protobuf versions

---

pyatv/mrp/__init__.py
pyatv/mrp/player_state.py
tests/fake_device/mrp.py
tests/mrp/test_mrp_functional.py

mrp: Maintain last known app name

---

base_versions.txt
docs/api/pyatv.html
docs/api/pyatv/interface.html
pyatv/__init__.py
pyatv/airplay/__init__.py
pyatv/airplay/pairing.py
pyatv/dmap/__init__.py
pyatv/dmap/pairing.py
pyatv/interface.py
pyatv/mrp/__init__.py
pyatv/mrp/pairing.py
pyatv/support/net.py
tests/airplay/test_airplay.py
tests/airplay/test_airplay_auth.py
tests/dmap/test_pairing.py
tests/utils.py

This commit makes the necessary changes to be compatible with aiohttp 4.
At least based on the latest pre-release. Additional changss might be
needed for final release.
Fixes #629.

cq: Support for aiohttp 4

---

docs/api/pyatv/interface.html
docs/development/power_management.md
pyatv/dmap/__init__.py
pyatv/interface.py
pyatv/mrp/__init__.py
tests/mrp/test_mrp_functional.py

power: Add await_new_state argument

---

.github/workflows/tests.yml

gha: Disable codecov as it's broken

---

pyatv/mrp/__init__.py
pyatv/mrp/player_state.py

mrp: Clean up player path handling

---

docs/api/pyatv.html
pyatv/__init__.py
pyatv/support/net.py
pyatv/support/udns.py
tests/airplay/test_airplay.py
tests/common_functional_tests.py
tests/conftest.py
tests/fake_udns.py
tests/scripts/script_env.py
tests/scripts/test_atvscript.py
tests/support/test_net.py
tests/support/test_udns.py
tests/test_scan.py
tests/utils.py

This is a very big change so I need to review it a bit more before merging.
Fixes #723.

scan: Custom scanning implementation

---

docs/api/pyatv.html
docs/api/pyatv/conf.html
docs/development/scan_pair_and_connect.md
docs/documentation/atvremote.md
docs/documentation/concepts.md
docs/index.md
docs/support/faq.md
pyatv/__init__.py
pyatv/conf.py
pyatv/support/udns.py
tests/fake_udns.py
tests/support/test_udns.py
tests/test_conf.py
tests/test_scan.py

With these changes a flag is added to the configuration that indicates if the device is deep sleeping.

Add support for deep sleep detection

---

docs/documentation/atvremote.md
pyatv/scripts/atvremote.py

atvremote: Add delay command

---

docs/api/pyatv/conf.html
pyatv/conf.py
pyatv/support/device_info.py
pyatv/support/mdns.py
pyatv/support/scan.py
tests/fake_udns.py
tests/support/dns_utils.py
tests/support/test_device_info.py
tests/support/test_mdns.py
tests/test_conf.py
tests/test_scan_functional.py

Extract device model from mdns

---

pyatv/dmap/pairing.py
tests/dmap/test_pairing.py
tests/fake_device/dmap.py

dmap: Fix pairing endpoint bug

---

CHANGES.md
docs/api/pyatv/const.html
docs/support/migration.md
pyatv/const.py

Release 0.7.0

---

.github/workflows/tests.yml
docs/api/pyatv/conf.html
docs/api/pyatv/helpers.html
docs/api/pyatv/interface.html
docs/pdoc_templates/html.mako
scripts/api.py
setup.py
tox.ini

gha: Run tests with python 3.9

---

docs/api/pyatv/exceptions.html
docs/documentation/concepts.md
docs/support/migration.md
pyatv/exceptions.py
pyatv/support/mdns.py
tests/support/test_mdns.py

scan: Remove check if host is on any local subnet

---

pyatv/scripts/atvremote.py
pyatv/support/__init__.py
pyatv/support/mdns.py
pyatv/support/net.py
tests/fake_udns.py
tests/support/test_mdns.py
tests/support/test_mdns_functional.py
tests/support/test_support.py

Improve scanning with new implementation

---

.github/workflows/tests.yml

Simple approach to deal with some unatableness when running pytest.

gha: Retry tox if first run fails

---

pyatv/support/mdns.py
tests/support/dns_utils.py
tests/support/test_mdns.py

mdns: Add support for authority records

---

pyatv/mrp/__init__.py
tests/mrp/test_mrp_functional.py
tests/utils.py

Compatibility with tvOS 14.
Fixes #791.

mrp: Require no ACK for HID messages

---

docs/api/pyatv.html
docs/support/faq.md
pyatv/__init__.py
pyatv/support/mdns.py
pyatv/support/scan.py
tests/support/test_mdns_functional.py
tests/support/test_scan.py

scan: Abort when device with identifier found

---

pyatv/support/mdns.py

An attempt to see if multicast works better.

mdns: Bind to port 5353 instead of random port

---

pyatv/mrp/messages.py
pyatv/mrp/protocol.py
tests/fake_device/mrp.py

mrp: Ack client updates messages

---

pyatv/mrp/__init__.py

mrp: Don't use deprecated home_hold internally

---

pyatv/support/mdns.py

mdns: Supress decoding errors

---

pyatv/support/__init__.py
pyatv/support/knock.py
pyatv/support/mdns.py
tests/support/test_mdns_functional.py

Mainly cleans up some debug logs in knock and mdns to be less spammy.

cq: Minor clean ups and fixes

---

pyatv/mrp/pairing.py
tests/mrp/test_mrp_auth.py

mrp: Verify credentials after pairing

---

.github/workflows/tests.yml

gha: Fix python 3.9 and use env files

---

pyatv/mrp/player_state.py
tests/fake_device/mrp.py
tests/mrp/test_mrp_functional.py

mrp: Handle UpdateClient before SetState

---

pyatv/mrp/__init__.py
pyatv/mrp/player_state.py
tests/fake_device/mrp.py

mrp: Improve client and player handling

---

pyatv/mrp/player_state.py
tests/fake_device/mrp.py
tests/mrp/test_mrp_functional.py
tests/mrp/test_player_state.py

Also inlcude tests for player_state, which I missed in #915. Ooops...

mrp: Fix a few playback state edge cases

---

docs/api/pyatv/interface.html
pyatv/dmap/__init__.py
pyatv/interface.py
pyatv/mrp/__init__.py
tests/test_interface.py

Do not post duplicate push updates

---

.github/workflows/tests.yml
pyatv/mrp/__init__.py
tests/mrp/test_mrp_functional.py

mrp: Add delay in turn_off between commands

---

pyatv/mrp/player_state.py
tests/fake_device/mrp.py
tests/mrp/test_mrp_functional.py
tests/mrp/test_player_state.py

mrp: Support default supported commands

---

pyatv/support/dns.py
pyatv/support/mdns.py
tests/support/test_dns.py

Unfortunately I was unable to add emoji to my Apple TV's name, but if Apple ever fixes that, this should handle that too.

Use UTF-8 for DNS names, and (attempt) to handle dots in names

---

tests/dmap/test_daap.py
tests/dmap/test_parser.py
tests/mrp/test_variant.py
tests/support/test_cache.py
tests/test_convert.py

cq: Convert more tests to pytest

---

pyatv/mrp/connection.py
pyatv/mrp/protocol.py
tests/conftest.py
tests/fake_device/__init__.py
tests/fake_device/mrp.py
tests/mrp/test_protocol.py

mrp: Add support for heartbeats

---

docs/api/pyatv/interface.html
pyatv/dmap/__init__.py
pyatv/dmap/daap.py
pyatv/interface.py
pyatv/mrp/__init__.py
tests/mrp/test_mrp_functional.py
tests/test_interface.py

Subclasses of Playing are no longer needed. This makes it easier to
maintain the immutability requirement.
Fixes #941.

if: Convert Playing to data class

---

pyatv/mrp/player_state.py
tests/mrp/test_player_state.py

mrp: Fix handling of active client

---

scripts/log2html.py

This is a MVP version that creates a simple HTML page from log input. It
supports reading from a file, stdin or with markdown syntax. Does not
handle large logs well for now.

log2html: New script converting logs to HTML pages

---

scripts/log2html.py

Instead of generating a static file, save log data as JSON and render it
dynamically with javascript. This is in preparation to support live
filtering on things like debug level and log content.

log2html: Render log entries with javascript

---

pyatv/mrp/protocol.py
tests/mrp/test_protocol.py
tests/utils.py

mrp: Add retry to heartbeats

---

pyatv/dmap/__init__.py
tests/common_functional_tests.py
tests/dmap/test_dmap_functional.py
tests/mrp/test_mrp_functional.py

dmap: Reset revision if push update fails

---

pyatv/scripts/atvproxy.py
pyatv/scripts/atvremote.py
pyatv/scripts/atvscript.py

scripts: Add module to log output

---

.gitignore
.gitpod.yml
README.md
scripts/build_docs.sh
scripts/setup_dev_env.sh

Updated scripts/setup_dev_env.sh to be more up to date. Made some
adjustments/workarounds for GitPod. Also enabled documentation again for
GitPod as Ruby is installed in the base Docker image, so no need for
DockerInDocker (with some modifications to the script).

env: Various updats to environment and GitPod

---

.github/workflows/tests.yml

No statistics is uploaded to Codecov othewise.

gha: Run tests workflow on master

---

pyatv/companion/server_auth.py
tests/companion/test_companion_auth.py
tests/fake_device/companion.py

companion: Add pairing function tests

---

docs/api/pyatv.html
docs/api/pyatv/exceptions.html
docs/api/pyatv/interface.html
docs/development/features.md
docs/documentation/concepts.md
pyatv/__init__.py
pyatv/airplay/__init__.py
pyatv/companion/__init__.py
pyatv/dmap/__init__.py
pyatv/exceptions.py
pyatv/interface.py
pyatv/mrp/__init__.py
pyatv/support/facade.py
pyatv/support/relayer.py
tests/common_functional_tests.py
tests/companion/test_companion_functional.py
tests/conftest.py
tests/mrp/test_mrp_functional.py
tests/support/test_facade.py
tests/support/test_relayer.py
tests/test_interface.py

This PR does pretty much everything mentioned in #1021. I'm gonna add more information regarding design in a separate commit.
Fixes #1021

Implement facade pattern for public interface

---

.github/ISSUE_TEMPLATE/bug_report.md
docs/support/faq.md

docs: Change "Apps" section to "Known Issues"

---

docs/api/pyatv/const.html
docs/api/pyatv/interface.html
docs/development/metadata.md
docs/documentation/atvremote.md
pyatv/const.py
pyatv/interface.py
pyatv/mrp/__init__.py
tests/fake_device/mrp.py
tests/mrp/test_mrp_functional.py
tests/scripts/test_atvscript.py
tests/test_interface.py

This PR adds series name, season and episode number to the public interface. An implementation is also provided for MRP (as that is the only protocol I know how to implement that for). Remember that this will only work if the app actually provides metadata correctly, something rarely done I'm afraid.

Add series name, season and episode number

---

pyatv/scripts/atvremote.py
pyatv/scripts/atvscript.py

Minor clean up to require less work when a new protocol is added.
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/1057"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

scripts: Protocol clean up

---

docs/_config.yml
docs/api/pyatv/const.html
docs/api/pyatv/interface.html
docs/development/audio.md
pyatv/const.py
pyatv/interface.py
pyatv/scripts/atvremote.py
pyatv/support/facade.py

Fixes #1069
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/1074"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

if: Add audio interface

---

base_versions.txt
docs/development/airplay.md
pyatv/raop/__init__.py
pyatv/raop/metadata.py
pyatv/raop/raop.py
pyatv/raop/rtsp.py

Fixes #1075
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/1080"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

raop: Use metadata from input file as metadata

---

docs/api/pyatv/interface.html
docs/development/examples.md
examples/stream.py
pyatv/raop/__init__.py
pyatv/raop/metadata.py
pyatv/raop/raop.py
pyatv/raop/rtsp.py

Fixes #1071
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/1084"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

raop: Implement Metadata and PushUpdater interface

---

pyatv/support/mdns.py
tests/fake_udns.py
tests/scripts/script_env.py
tests/support/dns_utils.py
tests/support/test_mdns.py
tests/support/test_mdns_functional.py
tests/test_scan_functional.py

Fixes #1087
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/1095"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Ignore link-local addresses when scanning

---

docs/api/pyatv/conf.html
docs/api/pyatv/const.html
docs/api/pyatv/interface.html
pyatv/conf.py
pyatv/const.py
pyatv/interface.py
pyatv/support/device_info.py
pyatv/support/scan.py
tests/support/test_mdns.py
tests/test_conf.py
tests/test_interface.py

Fixes #1090
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/1096"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

conf: Add device info for AirPort Express

---

pyatv/raop/raop.py
pyatv/raop/rtsp.py

Fixes #1086
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/1097"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

raop: Raise exception on RTSP error code

---

docs/documentation/supported_features.md
pyatv/raop/fifo.py
pyatv/raop/packets.py
pyatv/raop/raop.py
tests/raop/test_fifo.py

Buffer the last 1000 packets and re-send if requested by receiver.
Fixes #1079
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/1099"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

raop: Support retransmission of lost packets

---

pyatv/raop/miniaudio.py
pyatv/raop/raop.py

Fixes #1094
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/1100"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

raop: Set correct progress in metadata

---

docs/documentation/protocols.md
pyatv/companion/__init__.py
pyatv/companion/connection.py
pyatv/companion/pairing.py
pyatv/companion/protocol.py
tests/companion/test_companion_functional.py
tests/fake_device/companion.py

Relates to #1034
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/1106"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

companion: Fix case when app_list fails

---

pyatv/raop/__init__.py
pyatv/raop/metadata.py
pyatv/raop/miniaudio.py

Fixes #1113 
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/1121"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

raop: Do not perform I/O in event loop

---

pyatv/raop/raop.py
pyatv/raop/rtsp.py
tests/fake_device/raop.py
tests/raop/test_raop_functional.py

Relates to #1107
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/1119"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

raop: Send feedback if supported by receiver

---

base_versions.txt

Relates to #1133
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/1137"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

deps: Temporarily lock bitarray <2.1.1

---

docs/api/pyatv/interface.html
docs/documentation/supported_features.md
pyatv/interface.py
pyatv/raop/__init__.py
pyatv/raop/raop.py
pyatv/raop/rtsp.py
pyatv/support/__init__.py
pyatv/support/collections.py
pyatv/support/facade.py
pyatv/support/http.py
tests/fake_device/raop.py
tests/raop/test_raop_functional.py
tests/support/test_facade.py
tests/support/test_support.py

Fixes #1129
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/1135"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

raop: Add support for volume controls

---

pyatv/raop/raop.py
tests/raop/test_raop_functional.py

Relates to #1134
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/1145"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

raop: Only perform auth-setup for AirPort Express

---

.github/dependabot.yml
base_versions.txt
docs/_config.yml
docs/_includes/pypi
docs/api/pyatv/helpers.html
docs/documentation/documentation.md
docs/documentation/getting_started.md
docs/documentation/supported_features.md
docs/documentation/tutorial.md
docs/index.md
docs/internals/tools.md
docs/support/migration.md
pyatv/helpers.py
pyatv/raop/raop.py
pyatv/raop/rtsp.py
pyatv/support/scan.py
scripts/fake_device.py
tests/fake_device/raop.py
tests/raop/test_raop_functional.py
tests/support/test_scan.py
tests/test_helpers.py

Some minor things:
* Properly TEARDOWN RTSP session when done
* Fix RAOP service in fake_device
* Minor bug fixes and documentation updates
* Add a tutorial, explaining how to build a simple web client!
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/1151"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Various updates in preparation for 0.8.0

---

scripts/release.py

<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/1154"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

scripts: Generate new format in CHANGES.md

---

docs/development/examples.md
docs/documentation/tutorial.md
pylintrc

<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/1163"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

docs: Add tutorial as an example

---

setup.py

<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/1176"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

env: Update metadata in setup.py

---

docs/api/pyatv.html
docs/api/pyatv/conf.html
docs/api/pyatv/const.html
docs/api/pyatv/convert.html
docs/api/pyatv/exceptions.html
docs/api/pyatv/helpers.html
docs/api/pyatv/interface.html
docs/assets/css/custom.css
docs/pdoc_templates/config.mako
docs/pdoc_templates/html.mako
pyatv/dmap/__init__.py
pyatv/interface.py
tests/dmap/test_dmap_functional.py

Functions in the API that has the @feature decorator will now include
relevant FeatureName and all protocols implementing that feature in its
documentation.
Relates to #1197
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/1198"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

docs: Add feature name and supported protocols

---

docs/api/pyatv.html
pyatv/__init__.py

Relates to #1196
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/1222"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

core: Fix potential aiohttp client session leak

---

docs/api/pyatv.html
pyatv/__init__.py
pyatv/airplay/__init__.py
pyatv/airplay/pairing.py
pyatv/companion/__init__.py
pyatv/companion/connection.py
pyatv/companion/pairing.py
pyatv/dmap/__init__.py
pyatv/dmap/pairing.py
pyatv/mrp/__init__.py
pyatv/mrp/pairing.py

Move around code a bit to make creation of pairing handlers work like
setup and scan in protocols.
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/1225"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

cq: Refactor pairing handlers

---

pyatv/companion/__init__.py
pyatv/companion/protocol.py

Relates to #1210
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/1226"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

companion: Generalize OPACK error handling

---

docs/api/pyatv/conf.html
docs/development/stream.md
docs/documentation/atvremote.md
docs/documentation/supported_features.md
pyatv/conf.py
pyatv/raop/__init__.py
pyatv/raop/raop.py
pyatv/raop/rtsp.py
pyatv/scripts/atvremote.py
pyatv/support/http.py
tests/fake_device/raop.py
tests/raop/test_raop_functional.py

This pull request implements support for password protected RAOP devices. I'm ready to implement any changes / cleanups that are required.
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/1212"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

[RAOP] Add support for password protected devices

---

docs/documentation/supported_features.md

<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/1244"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

docs: Fix broken links in supported_features

---

docs/support/faq.md

Relates to #1249
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/1250"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

docs: Add entry for Illegal instruction

---

docs/support/faq.md

Relates to #1160
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/1166"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

docs: Add issue regarding cellcomtvappleos

---

docs/documentation/protocols.md

This is the initial documentation for how the remote control support
works in AirPlay 2. It is not complete and aims to serve as help for
getting started with implementing support for it.
Relates to #1255
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/1257"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

docs: Add remote control docs for AirPlay 2

---

docs/documentation/protocols.md

Relates to #1255
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/1258"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

docs: Fix broken diagram in AP 2

---

docs/documentation/protocols.md

Relates to #1255
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/1266"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

docs: Make some clarifications for AirPlay remote

---

docs/api/pyatv/conf.html
pyatv/conf.py
tests/test_conf.py

Relates to #1273
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/1274"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

conf: Add password to RAOP output

---

docs/api/pyatv/helpers.html
docs/development/stream.md
pyatv/helpers.py
tests/test_helpers.py

Relates to #1241
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/1275"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

helpers: Add is_streamable method

---

docs/documentation/concepts.md
docs/documentation/supported_features.md
pyatv/mrp/__init__.py
tests/fake_device/mrp.py
tests/mrp/test_mrp_functional.py

Relates to #1279
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/1286"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

mrp: Extract build number from DEVICE_INFO

---

.github/workflows/packages.yml
scripts/version.py

Experiment to build Docker containers with pyatv for amd64, arm64 and
armv7. Will have to fiddle until I have something working as it's hard
to try Actions without merging them. As a test, this action is only
triggered on the "test" branch.
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/1288"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

gha: Build and publish Docker containers

---

.github/workflows/release.yml
Dockerfile
pyatv/scripts/atvremote.py
scripts/version.py

This fixes building of containers (missing Dockerfile). If containers
were built from a tag, it is assumed to be a release and a GitHub
release will be created.
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/1290"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

gha: Fix building containers and make releases

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/investigation.yml

Relates to #1219
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/1294"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

gh: Fix bad labels for investigation and bugs

---

docs/api/pyatv/interface.html
pyatv/interface.py
tests/test_interface.py

Never go below 0 or above total_time.
Relates to #1283
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/1296"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

if: Keep position within limits

---

.github/workflows/tests.yml

Needed to manually trigger runs on specific branches.
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/1304"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

gha: Add workflow_dispatch: to tests workflow

---

docs/api/pyatv.html
docs/development/scan_pair_and_connect.md
pyatv/__init__.py
pyatv/core/scan.py
pyatv/scripts/__init__.py
pyatv/scripts/atvremote.py
tests/scripts/test_atvremote.py
tests/test_scan_functional.py

Relates to #1338
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/1340"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

scan: Support scanning for multiple identifiers

---

pyatv/protocols/companion/__init__.py
tests/protocols/companion/test_companion.py

Relates to #1336
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/1342"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

companion: Improve pairing requirement detection

---

docs/api/pyatv/const.html
docs/api/pyatv/convert.html
docs/api/pyatv/interface.html
pyatv/const.py
pyatv/convert.py
pyatv/core/scan.py
pyatv/interface.py
pyatv/protocols/__init__.py
pyatv/protocols/airplay/__init__.py
pyatv/protocols/companion/__init__.py
pyatv/protocols/dmap/__init__.py
pyatv/protocols/mrp/__init__.py
pyatv/protocols/raop/__init__.py
tests/protocols/airplay/test_airplay.py
tests/protocols/companion/test_companion.py
tests/protocols/dmap/test_dmap.py
tests/protocols/dmap/test_dmap_functional.py
tests/protocols/mrp/test_mrp.py
tests/protocols/raop/test_raop.py
tests/test_convert.py
tests/test_interface.py

Relates to #1341
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/1345"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

dmap: Add device model Music for Music/iTunes

---

pyatv/protocols/airplay/__init__.py
pyatv/protocols/airplay/remote_control.py
pyatv/protocols/airplay/utils.py
tests/protocols/airplay/test_utils.py

Relates to #1359
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/1361"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

airplay: Handle semver version in osvers

---

pyatv/protocols/airplay/__init__.py
pyatv/protocols/companion/__init__.py
pyatv/protocols/dmap/__init__.py
pyatv/protocols/mrp/__init__.py
pyatv/protocols/raop/__init__.py
tests/fake_udns.py
tests/support/test_device_info.py
tests/test_scan_functional.py

Relates to #1357
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/1362"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

mrp: Ignore service during scan for tvOS >= 15

---

docs/documentation/atvremote.md

Relates to #1360
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/1363"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

docs: Add docs for app_list and launch_app

---

pyatv/interface.py
tests/test_conf.py

Relates to #1417
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/1443"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

conf: Ignore services with missing identifier

---

.gitpod.yml
chickn.yaml
docs/internals/tools.md
scripts/chickn.py

chickn fails because PIP_USER is set (so packages are not installed).
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/1488"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

env: Fix broken GitPod integration

---

docs/documentation/protocols.md
pyatv/protocols/companion/opack.py
tests/protocols/companion/test_opack.py

Relates to #1489
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/1491"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

opack: Handle pointers properly

---

docs/api/pyatv/interface.html
docs/development/stream.md
docs/documentation/supported_features.md
pyatv/interface.py
pyatv/protocols/raop/__init__.py
pyatv/protocols/raop/audio_source.py

Relates to #1482
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/1490"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

raop: Support streaming from HTTP(s)

---

pyatv/auth/hap_pairing.py
pyatv/auth/hap_srp.py
pyatv/protocols/airplay/auth/hap.py
pyatv/protocols/airplay/auth/legacy.py
pyatv/protocols/airplay/mrp_connection.py
pyatv/protocols/mrp/__init__.py
pyatv/protocols/mrp/auth.py
pyatv/protocols/mrp/connection.py
pyatv/protocols/mrp/protocol.py

Added more typehints to make it more clear that the method was missing.
Fixes #1505
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/1506"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

mrp: Add enable_encryption to connection

---

base_versions.txt
pyatv/protocols/dmap/pairing.py
pyatv/support/net.py
pylintrc
pyproject.toml
requirements/requirements.txt
scripts/setup_dev_env.sh
tests/conftest.py
tests/support/test_net.py

Relates to #1509
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/1520"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

dep: Migrate from netifaces to ifaddr

---

pyatv/protocols/raop/raop.py

Only start logging "too slow to keep up" errors after getting at least
three in a row to be less chatty. Getting a few is generally not a
problem as pyatv will catch up.
Relates to #1531
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/1540"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

raop: Make slowness warnings less chatty

---

pyatv/core/facade.py
tests/core/test_facade.py

Relates to #1538
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/1543"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

facade: Stop push updaters on close

---

pyatv/support/knock.py
tests/support/test_knock.py

Ensure knock exceptions are retrieved

---

docs/documentation/protocols.md

some amendments for you. 
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/1613"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Fixes and amendments to protocols doc.

---

pyatv/protocols/companion/__init__.py

Relates to #1586
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/1600"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

companion: Fix pairing requirement flag

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/workflows/tests.yml
docs/documentation/documentation.md
setup.py

Relates to #1587
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/1588"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

deps: Deprecate python 3.6

---

docs/index.md

Adding nodered pyatv to the list of projects.
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/1646"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Adding a project to the list

---

pyatv/support/net.py

Relates to #1773
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/1774"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

mdns: Suppress exceptions properly

---

pyatv/scripts/atvscript.py

Fixes #1930
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/1962"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

atvscript: Check app support before printing

---

docs/api/pyatv/interface.html
docs/development/listeners.md
docs/documentation/atvscript.md
pyatv/core/facade.py
pyatv/interface.py
pyatv/scripts/atvscript.py
tests/core/test_facade.py
tests/protocols/mrp/test_mrp_interface.py

Adds a listener interface to `Audio`, to enable push updates for volume changes as recommended in https://github.com/postlund/pyatv/issues/1798#issuecomment-1188276550
Resolves #1798

Add listener interface to Audio for volume updates

---

pyatv/protocols/mrp/__init__.py
tests/protocols/mrp/test_mrp_interface.py

… even if playing to other AirPlay devices in a group.
Fixes: #2005
Instead of updating `self._output_device_id` when we get a `VOLUME_CONTROL_CAPABILITIES_DID_CHANGE_MESSAGE` (which may be the UID of another grouped AirPlay device), just always use the one from device info which we get when the protocol starts.

Make sure were sending and receiving volume messages for our device

---

docs/api/pyatv/interface.html
docs/development/audio.md
docs/development/listeners.md
docs/development/stream.md
pyatv/core/facade.py
pyatv/interface.py
pyatv/protocols/raop/__init__.py
pyatv/protocols/raop/audio_source.py

Fixes #1997
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/2010"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

raop: Support asyncio StreamReader when streaming

---

docs/api/pyatv/const.html
pyatv/const.py
pyatv/convert.py
pyatv/interface.py
pyatv/support/device_info.py
tests/test_convert.py
tests/test_interface.py

Add Apple TV 4k (gen3):
https://www.theiphonewiki.com/wiki/J255AP
Add new tvOS versions:
https://en.wikipedia.org/wiki/TvOS#tvOS_16

Add Apple TV 4k (gen3) and new tvOS versions

---

base_versions.txt
docs/api/pyatv/const.html
docs/api/pyatv/interface.html
pyatv/const.py
pyatv/core/facade.py
pyatv/interface.py
pyatv/protocols/companion/__init__.py
requirements/requirements.txt
tests/fake_device/companion.py
tests/protocols/companion/test_companion_functional.py

Fixes #1839
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/2041"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

companion: Add screensaver support

---

pyatv/protocols/airplay/utils.py
tests/protocols/airplay/test_utils.py
tests/support/test_metadata.py

Fixes #2075 
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/2077"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

airplay: Fix AirPlay major version detection

---

docs/api/pyatv.html
docs/api/pyatv/interface.html
docs/api/pyatv/settings.html
docs/pdoc_templates/html.mako

Seems like some pages related to storage aren't working, not sure why since it works locally. Trying to fix...
Relates to #243
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/2159"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

docs: Try to fix API docs for some modules

---

base_versions.txt
docs/api/pyatv.settings.html
pyatv/settings.py
requirements/requirements.txt

Relates to #243
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/2165"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

storage: Use pydantic-extra-types for MAC

---

docs/api/pyatv.conf.html
docs/api/pyatv.const.html
docs/api/pyatv.convert.html
docs/api/pyatv.exceptions.html
docs/api/pyatv.helpers.html
docs/api/pyatv.html
docs/api/pyatv.interface.html
docs/api/pyatv.settings.html
docs/api/pyatv.storage.file_storage.html
docs/api/pyatv.storage.html
docs/api/pyatv.storage.memory_storage.html
docs/pdoc_templates/html.mako

Relates to #243
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/2168"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

docs: More link fixes

---

docs/api/pyatv.settings.html
pyatv/protocols/raop/__init__.py
pyatv/protocols/raop/stream_client.py
pyatv/settings.py

Relates to #1910
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/2180"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

raop: Add settings for timing and control ports

---

.github/ISSUE_TEMPLATE/minor-change.yml
.github/ISSUE_TEMPLATE/question-or-idea.yml

Relates to #2129
<a href="https://gitpod.io/#https://github.com/postlund/pyatv/pull/2183"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

docs: Add minor change template

---

base_versions.txt
docs/api/pyatv.settings.html
docs/api/pyatv.storage.html
docs/pdoc_templates/html.mako
pyatv/interface.py
pyatv/protocols/mrp/protobuf/CommandInfo_pb2.pyi
pyatv/protocols/mrp/protobuf/Common_pb2.pyi
pyatv/protocols/mrp/protobuf/ContentItemMetadata_pb2.pyi
pyatv/protocols/mrp/protobuf/DeviceInfoMessage_pb2.pyi
pyatv/protocols/mrp/protobuf/KeyboardMessage_pb2.pyi
pyatv/protocols/mrp/protobuf/ModifyOutputContextRequestMessage_pb2.pyi
pyatv/protocols/mrp/protobuf/Origin_pb2.pyi
pyatv/protocols/mrp/protobuf/ProtocolMessage_pb2.pyi
pyatv/protocols/mrp/protobuf/RegisterForGameControllerEventsMessage_pb2.pyi
pyatv/protocols/mrp/protobuf/SendCommandResultMessage_pb2.pyi
pyatv/protocols/mrp/protobuf/SendPackedVirtualTouchEventMessage_pb2.pyi
pyatv/protocols/mrp/protobuf/SetConnectionStateMessage_pb2.pyi
pyatv/protocols/mrp/protobuf/SetRecordingStateMessage_pb2.pyi
pyatv/protocols/mrp/protobuf/TextInputMessage_pb2.pyi
pyatv/protocols/mrp/protobuf/VolumeControlAvailabilityMessage_pb2.pyi
pyatv/settings.py
pyatv/storage/__init__.py
pyatv/storage/file_storage.py
pyatv/support/__init__.py
pyatv/support/pydantic_compat.py
requirements/requirements.txt
tests/support/test_support.py
tests/test_storage_functional.py

Use pydantic v1 compatibility when with pydantic v2

---

docs/support/acknowledgements.md

This PR should be self-explanatory :)

update the list of contributors

---

docs/index.md

Added link to atv-desktop-remote following discussion here: https://github.com/postlund/pyatv/issues/2398

Update index.md to add link to atv-desktop-remote (project that uses pyatv)

---

docs/documentation/atvremote.md
tests/protocols/companion/test_companion_functional.py

cq: Minor updates

---

docs/api/pyatv.const.html
docs/api/pyatv.convert.html
pyatv/const.py
pyatv/convert.py
pyatv/support/device_info.py
tests/support/test_device_info.py
tests/test_convert.py

Add Apple TV 1, update some tables and fix OS bug.
Relates to #2517

core: Update device info

---

.github/workflows/release.yml

gha: Update upload-artifact to v4
